/* ─── TAB SWITCHING ─── */
document.querySelectorAll('.nav-tab').forEach(tab => {
  tab.addEventListener('click', () => {
    const target = tab.dataset.page;

    document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));
    tab.classList.add('active');

    /* ── Fondo según página ── */
    document.body.classList.remove('page-carta', 'page-vinos');
    document.body.classList.add(`page-${target}`);

    document.querySelectorAll('.page').forEach(p => {
      p.classList.remove('active', 'entering');
    });

    const page = document.getElementById(target);
    if (page) {
      page.classList.add('active');
      void page.offsetWidth;
      page.classList.add('entering');
    }

    window.scrollTo({ top: 0, behavior: 'smooth' });

    revealVisible();
    staggerItems();
  });
});

/* ─── SCROLL REVEAL ─── */
function revealVisible() {
  const els = document.querySelectorAll(
    '.page.active [data-section], .page.active .allergen-legend'
  );

  if ('IntersectionObserver' in window) {
    const io = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
          io.unobserve(entry.target);
        }
      });
    }, { threshold: 0, rootMargin: '0px 0px -5% 0px' });

    els.forEach(el => {
      if (!el.classList.contains('visible')) io.observe(el);
    });
  } else {
    els.forEach(el => el.classList.add('visible'));
  }
}

/* ─── ITEM ROW STAGGER ─── */
function staggerItems() {
  document.querySelectorAll('.page.active .item').forEach((item, i) => {
    item.style.transitionDelay = `${Math.min(i * 18, 220)}ms`;
  });
}

/* ─── STICKY HERO SHRINK ─── */
const hero = document.querySelector('.hero-inner');
let lastScroll = 0;

window.addEventListener('scroll', () => {
  const y = window.scrollY;
  if (y > 60 && lastScroll <= 60) {
    hero.style.paddingTop    = '1.2rem';
    hero.style.paddingBottom = '1rem';
    hero.style.transition    = 'padding 0.3s ease';
  } else if (y <= 60 && lastScroll > 60) {
    hero.style.paddingTop    = '2.5rem';
    hero.style.paddingBottom = '1.8rem';
  }
  lastScroll = y;
}, { passive: true });

/* ─── INIT ─── */
document.addEventListener('DOMContentLoaded', () => {
  revealVisible();
  staggerItems();
  /* Fallback: fuerza visible en secciones muy largas */
  setTimeout(() => {
    document.querySelectorAll('.menu-section, .allergen-legend').forEach(el => {
      const rect = el.getBoundingClientRect();
      if (rect.top < window.innerHeight * 2) el.classList.add('visible');
    });
  }, 300);
});

window.translations = {
  "es": {
    "section-title-0": "Tablas",
    "section-title-1": "Tostas",
    "section-title-2": "Del Corral",
    "section-title-3": "Los Fritos",
    "section-title-4": "Seguimos picando…",
    "section-title-5": "Ensaladas",
    "section-title-6": "Del Mar",
    "section-title-7": "De la Tierra",
    "section-title-8": "Veganos y Vegetarianos",
    "section-title-9": "Despedida Dulce",
    "section-title-10": "Blancos Gallegos",
    "section-title-11": "Tintos Gallegos",
    "section-title-12": "Champanes y Espumosos",
    "section-title-13": "Ribera del Duero",
    "section-title-14": "Toro",
    "section-title-15": "Castilla y León",
    "section-title-16": "Riojas",
    "wine-subregion-0": "Monterrei",
    "wine-subregion-1": "Valdeorras",
    "wine-subregion-2": "Bierzo",
    "wine-subregion-3": "Albariños",
    "wine-subregion-4": "Ribeiros",
    "wine-subregion-5": "Godello",
    "wine-subregion-6": "Mencías y Tintos Gallegos",
    "section-note-0": "Con aceite de oliva y vinagre de módena",
    "section-note-1": "Uva principal: Tempranillo (Tinto Fino) salvo indicación contraria",
    "section-note-2": "Uva principal: Tinta de Toro (clon local del Tempranillo) salvo indicación contraria",
    "section-note-3": "Uva principal: Tempranillo salvo indicación contraria",
    "item-name-0": "Jamón Ibérico",
    "item-name-1": "Jamón Ibérico con queso semicurado",
    "item-name-2": "De Ibéricos (Jamón, chorizo, salchichón y lomo)",
    "item-name-3": "De Quesos (Tetilla, semicurado, San Simón con almendras y membrillo)",
    "item-name-4": "Rulo de cabra, cebolla caramelizada, beicon y nueces, salsa sweet chili y módena",
    "item-name-5": "Atún, pimientos de piquillo confitados, salsa de pimientos y módena",
    "item-name-6": "Salmón ahumado, queso fresco, brotes de ensalada, salsa de pimientos y módena",
    "item-name-7": "Sobrasada mallorquina, brie, cebolla crujiente, salsa de pimientos y módena",
    "item-name-8": "Anchoas, mermelada de pimientos, tetilla y pimientos de piquillo",
    "item-name-9": "Setas, jamón y tomate con aceite y perejil, salsa de pimientos y módena",
    "item-name-10": "Huevos de corral con jamón y patatas",
    "item-name-11": "Huevos de corral con choricitos y patatas",
    "item-name-12": "Huevos de corral con solomillo de cerdo ibérico, patatas y salsa de setas",
    "item-name-13": "Huevos de corral con secreto ibérico, patatas y jamón",
    "item-name-14": "Revuelto de setas con gambones",
    "item-name-15": "Revuelto de bacalao con piquillo",
    "item-name-16": "Revuelto de gulas y gambas",
    "item-name-17": "Chipirones en fritura de harina de maíz y ali-oli de ajo negro",
    "item-name-18": "Croquetas caseras (consultar variedad)",
    "item-name-19": "Langostinos crujientes en panko con mayonesa agridulce",
    "item-name-20": "Alitas de pollo con salsa de mostaza y miel",
    "item-name-21": "Dados de pollo salteados, manzana, salsa teriyaki, cebolla caramelizada y patatas",
    "item-name-22": "Patatas bravas y ali-oli",
    "item-name-23": "Choquitos a la plancha, aceite de ajo y perejil y ali-oli de pimientos",
    "item-name-24": "Tortilla de patatas",
    "item-name-25": "Salteado de setas y gambas",
    "item-name-26": "Anchoas del Cantábrico sobre tomate rallado y orégano",
    "item-name-27": "Vieras del Pacífico a la plancha con aliño de ajo y perejil",
    "item-name-28": "Cazuelita de setas y gambas al ajillo",
    "item-name-29": "De hojas tiernas, piquillos y ventresca de bonito y espárragos",
    "item-name-30": "Mezclum de lechugas (con queso camembert frito y mermelada de higos)",
    "item-name-31": "De jamón, queso semicurado y frutos secos",
    "item-name-32": "Templada de vieiras del Atlántico y langostinos con frutos secos",
    "item-name-33": "Bacalao al horno con setas y castañas",
    "item-name-34": "Bacalao a la parrilla con salteado de verduras al wok",
    "item-name-35": "Lomo de merluza a la plancha con ensalada de temporada",
    "item-name-36": "Tentáculo de pulpo a la parrilla",
    "item-name-37": "Picaña de vacuno a la parrilla",
    "item-name-38": "Entrecot de ternera gallega a la parrilla con salsa a la pimienta",
    "item-name-39": "Secreto de cerdo ibérico con salsa BBQ",
    "item-name-40": "Chuletón de vacuno mayor (por encargo)",
    "item-name-41": "Variado de carnes: Entrecot, secreto y picaña (mín. 2 personas)",
    "item-name-42": "Hamburguesa de buey con queso cheddar, beicon y lechuga",
    "item-name-43": "Pan por persona",
    "item-name-44": "Verduras a la plancha (tomate, cebolla, pimientos, calabacín y setas)",
    "item-name-45": "Salteado de verduras (tomate, cebolla, pimientos, calabacín, berenjena, setas, ajo y perejil)",
    "item-name-46": "Arroz con leche",
    "item-name-47": "Coulant de chocolate con helado de vainilla",
    "item-name-48": "Tarta de queso semifría con mermelada de fresa",
    "item-name-49": "Tiramisú",
    "item-name-50": "Tarta de la abuela",
    "item-name-51": "Flan de café",
    "item-name-52": "Ladairo Godello",
    "item-name-53": "Crego Monaguillo",
    "item-name-54": "3 Mentiras",
    "item-name-55": "Godeval",
    "item-name-56": "O Luar do Sil",
    "item-name-57": "O Luar do Sil sobre Lías",
    "item-name-58": "Valtuille El Val",
    "item-name-59": "Mar de Nudos",
    "item-name-60": "Sentidiño",
    "item-name-61": "Goda",
    "item-name-62": "Gran Novas",
    "item-name-63": "Albamar Osebal",
    "item-name-64": "Davide",
    "item-name-65": "Viña Costeira Treixadura",
    "item-name-66": "Razamonde",
    "item-name-67": "Catro Ferrados",
    "item-name-68": "Valdesil Montenovo",
    "item-name-69": "Louro",
    "item-name-70": "La Llorona",
    "item-name-71": "Val de Sil 2023",
    "item-name-72": "Crego Monaguillo Monterrei",
    "item-name-73": "Ladairo Monterrei",
    "item-name-74": "3 Mentiras Monterrei",
    "item-name-75": "Fusco",
    "item-name-76": "Fulcro Alixe",
    "item-name-77": "Abeledos",
    "item-name-78": "Valtuille Bierzo",
    "item-name-79": "Pittacum Mencía",
    "item-name-80": "Cotarello Ribeiro (tinto)",
    "item-name-81": "AAA Tinto",
    "item-name-82": "Petalos del Bierzo",
    "item-name-83": "Attis Souson Rías Baixas",
    "item-name-84": "Heritage Blanc",
    "item-name-85": "Carramimbre Roble",
    "item-name-86": "Martín Berdugo Barrica",
    "item-name-87": "822",
    "item-name-88": "Coto Haya Centenario",
    "item-name-89": "Finca Resalso",
    "item-name-90": "Prios",
    "item-name-91": "Resalso Roble",
    "item-name-92": "Santa María",
    "item-name-93": "Tamaral Roble",
    "item-name-94": "Ceres",
    "item-name-95": "Valtravieso",
    "item-name-96": "Capellanes Roble",
    "item-name-97": "CLON 98",
    "item-name-98": "Ébano Salvaje",
    "item-name-99": "Viña Sastre",
    "item-name-100": "Carmelo Rodero 9 Meses",
    "item-name-101": "Tamaral Crianza",
    "item-name-102": "Martín Berdugo Crianza",
    "item-name-103": "Silvanus",
    "item-name-104": "Conde de San Cristóbal",
    "item-name-105": "La Cebolleta",
    "item-name-106": "Corimbo",
    "item-name-107": "Cair Finca Aguilera",
    "item-name-108": "Capellanes Crianza",
    "item-name-109": "Carmelo Rodero Crianza",
    "item-name-110": "Teófilo Reyes",
    "item-name-111": "Altamimbre",
    "item-name-112": "Convento San Francisco 2019",
    "item-name-113": "Arzuaga Crianza",
    "item-name-114": "La Felisa Emilio Moro",
    "item-name-115": "Cair Cuve Magnum",
    "item-name-116": "La Pinnaleta",
    "item-name-117": "Malleolus",
    "item-name-118": "Abadía Retuerta Selección Especial",
    "item-name-119": "Francisco Barona",
    "item-name-120": "Tomás Postigo 3 Año",
    "item-name-121": "Valduero I Cepa",
    "item-name-122": "A&M Asenjo Manso",
    "item-name-123": "Garmón 2019",
    "item-name-124": "Pago Carraovejas",
    "item-name-125": "Punto Geodésico",
    "item-name-126": "Raza Carmelo Rodero",
    "item-name-127": "Aalto",
    "item-name-128": "Dehesa Canónigos Solideo",
    "item-name-129": "Valduero Alta RVA",
    "item-name-130": "Un Sueño Pago de los Capellanes",
    "item-name-131": "Arzuaga Reserva Especial 2018",
    "item-name-132": "Tomás Postigo 5º Año",
    "item-name-133": "Tomás Postigo Magnum 3 Año",
    "item-name-134": "Francisco Barona Finca Las Dueñas",
    "item-name-135": "Sed de Caña",
    "item-name-136": "Aalto PS",
    "item-name-137": "Malleolus Valderramiro",
    "item-name-138": "Valduero Gran RVA",
    "item-name-139": "Luis Sanz Gran RVA",
    "item-name-140": "Tomás Postigo Rebollo Magnum",
    "item-name-141": "Valbuena 5º",
    "item-name-142": "Tomás Postigo Vinificación Integral Magnum",
    "item-name-143": "Doroteo Pago de los Capellanes",
    "item-name-144": "La Rejadora",
    "item-name-145": "Prima",
    "item-name-146": "Lorca Malbec",
    "item-name-147": "San Román",
    "item-name-148": "Platón Divina",
    "item-name-149": "Latarce",
    "item-name-150": "Syrah Matasnos",
    "item-name-151": "Pintia",
    "item-name-152": "Cartago",
    "item-name-153": "Alquez",
    "item-name-154": "Museum RVA",
    "item-name-155": "Albeniz Torre",
    "item-name-156": "Sommos Colección Syrah",
    "item-name-157": "Mauro",
    "item-name-158": "Mauro VS",
    "item-name-159": "Terreus",
    "item-name-160": "El Maquinista",
    "item-name-161": "Rioja Ondarre Crianza",
    "item-name-162": "Amador Medrano Los Sotillos",
    "item-name-163": "Bai Gorri",
    "item-name-164": "Beronia Edición Limitada",
    "item-name-165": "Amador Medrano Las Aguzaderas",
    "item-name-166": "La Montesa",
    "item-name-167": "Amaren",
    "item-name-168": "Luis Cañas Reserva 2018",
    "item-name-169": "Murua Rioja",
    "item-name-170": "Colección Privada Beronia",
    "item-name-171": "Los Sotillos",
    "item-name-172": "Macán Oro",
    "item-name-173": "Macán Clásico",
    "wine-grape-0": "Godello — elegante y untuoso, con acidez vibrante y fondo cítrico",
    "wine-grape-1": "Godello — expresivo, con aromas a fruta de hueso y notas almendradas al final",
    "wine-grape-2": "Godello, Doña Blanca, Treixadura — fresco y mineral con notas de hierba y flor blanca",
    "wine-grape-3": "Godello — referencia de la D.O., limpio y fresco con toques florales y mineral",
    "wine-grape-4": "Godello — amplio y elegante, con matices de fruta madura y mineral de pizarra",
    "wine-grape-5": "Godello — crianza sobre lías que aporta cremosidad, complejidad y gran persistencia",
    "wine-grape-6": "Godello — finca singular en el Bierzo, mineral y tenso con una acidez perfecta",
    "wine-grape-7": "Albariño — vino de entrada que transmite el carácter atlántico de la D.O. Rías Baixas",
    "wine-grape-8": "Albariño — fresco y aromático, fácil de beber con buena relación calidad-precio",
    "wine-grape-9": "Albariño — joven y atlántico, con notas cítricas, melocotón y un toque salino",
    "wine-grape-10": "Albariño — expresivo y frutal, con buena acidez y fondo herbal",
    "wine-grape-11": "Albariño — de O Salnés, muy frutal, fresco y limpio con final persistente",
    "wine-grape-12": "Albariño — elegante y complejo, con crianza que le aporta profundidad y carácter",
    "wine-grape-13": "Treixadura — variedad reina del Ribeiro, fresca y floral con un final sutil y limpio",
    "wine-grape-14": "Treixadura — de viñas en ladera, vivo y mineral con un toque de hierba aromática",
    "wine-grape-15": "Treixadura, Godello, Albariño — coupage de variedades autóctonas del Ribeiro con mucha expresión",
    "wine-grape-16": "Godello — joven y directo, con la acidez y mineralidad característica de Valdeorras",
    "wine-grape-17": "Godello — crianza en barrica que aporta complejidad y tostados elegantes",
    "wine-grape-18": "Godello — singular y de autor, con carácter atlántico muy marcado y gran frescura",
    "wine-grape-19": "Godello — de Valdeorras, expresivo y tenso con acidez vibrante y final mineral",
    "wine-grape-20": "Mencía — fresco y frutal, con notas de cereza y violeta típicas de esta variedad galega",
    "wine-grape-21": "Mencía — elegante y mineral, con taninos suaves y un final largo y especiado",
    "wine-grape-22": "Mencía — jugoso y accesible, con buena fruta roja y fondo herbáceo de terroir",
    "wine-grape-23": "Mencía — joven y goloso, con fruta fresca y taninos suaves ideales para el aperitivo",
    "wine-grape-24": "Mencía — de la Ribeira Sacra, mineral y vertical con la elegancia del terroir de granito",
    "wine-grape-25": "Mencía — de viñas en ladera de la Ribeira Sacra, mineral y tenso con fruta concentrada",
    "wine-grape-26": "Mencía — del Bierzo, floral y muy perfumado con taninos sedosos y acidez vibrante",
    "wine-grape-27": "Mencía — frescos aromas de fruta roja y violeta con taninos elegantes del Bierzo",
    "wine-grape-28": "Brancellao, Sousón, Ferrón — coupage de tintas autóctonas del Ribeiro, único y expresivo",
    "wine-grape-29": "Mencía, Garnacha Tintorera — coupage potente y expresivo con fruta negra madura",
    "wine-grape-30": "Mencía — de Álvaro Palacios, floral y elegante, considerado referencia mundial de la variedad",
    "wine-grape-31": "Sousón — variedad autóctona gallega recuperada, intensa y compleja con gran carácter",
    "wine-grape-32": "Chardonnay, Pinot Noir, Pinot Meunier — champán de estilo clásico, fresco y equilibrado",
    "wine-grape-33": "Tinto Fino — joven con paso por roble, accesible y frutal con notas de madera bien integradas",
    "wine-grape-34": "Tinto Fino — paso suave por barrica, joven y frutal con carácter propio de la zona de Aranda",
    "wine-grape-35": "Tinto Fino — vino de entrada de Bodegas Emilio Moro, afrutado y de fácil bebida",
    "wine-grape-36": "Tinto Fino — de viñas centenarias, concentrado y profundo con mucha personalidad de terroir",
    "wine-grape-37": "Tinto Fino — de Emilio Moro, de finca propia, joven y concentrado con mucha fruta roja",
    "wine-grape-38": "Tinto Fino — fresco y frutal de Bodegas Prios Maximus, con buena relación calidad-precio",
    "wine-grape-39": "Tinto Fino — de Emilio Moro, paso por roble con fruta muy viva y accesible",
    "wine-grape-40": "Tinto Fino — de Convento San Francisco, joven y accesible con notas de fruta fresca",
    "wine-grape-41": "Tinto Fino — paso por roble de Bodegas Tamaral, fresco y frutal con toque especiado",
    "wine-grape-42": "Tinto Fino — vino de terroir, mineral y fresco con una buena acidez natural",
    "wine-grape-43": "Tinto Fino, Cabernet Sauvignon, Merlot — moderno y frutal con presencia internacional",
    "wine-grape-44": "Tinto Fino — paso breve por roble, frutal y accesible, de uno de los referentes de la D.O.",
    "wine-grape-45": "Tinto Fino — de las añadas más longevas de la D.O., con fruta madura y buena guarda",
    "wine-grape-46": "Tinto Fino — de viñas silvestres, carácter salvaje y mineral con gran autenticidad",
    "wine-grape-47": "Tinto Fino — de viñas viejas en La Horra, elegante y terroirista con mucho carácter",
    "wine-grape-48": "Tinto Fino — 9 meses en barrica, potente y especiado con una gran personalidad",
    "wine-grape-49": "Tinto Fino — crianza de Bodegas Tamaral, equilibrado y gastronómico con buena estructura",
    "wine-grape-50": "Tinto Fino — crianza clásica, equilibrado y muy versátil para acompañar carnes y quesos",
    "wine-grape-51": "Tinto Fino — de Bodegas Valduero, elegante y mineral con una gran expresión del terroir",
    "wine-grape-52": "Tinto Fino, Cabernet Sauvignon, Merlot — moderno y aterciopelado con notas de fruta negra y especias",
    "wine-grape-53": "Tinto Fino — de viña única centenaria, concentrado y terroirista con mucha personalidad",
    "wine-grape-54": "Tinto Fino — de Bodegas Rivera, potente y generoso con fruta negra madura y roble bien integrado",
    "wine-grape-55": "Tinto Fino — de finca singular, mineral y elegante con crianza en roble francés",
    "wine-grape-56": "Tinto Fino — crianza clásica en roble americano y francés, equilibrado y muy elegante",
    "wine-grape-57": "Tinto Fino, Cabernet Sauvignon — crianza clásica con mucha estructura y largo final especiado",
    "wine-grape-58": "Tinto Fino — crianza de autor con largas maceraciones, potente y muy expresivo",
    "wine-grape-59": "Tinto Fino — expresivo y concentrado, con crianza en roble francés y americano",
    "wine-grape-60": "Tinto Fino — versión de mayor crianza, complejo y mineral con largo final en boca",
    "wine-grape-61": "Tinto Fino, Cabernet Sauvignon, Merlot — clásico y equilibrado, con taninos bien integrados",
    "wine-grape-62": "Tinto Fino — de finca propia de Emilio Moro, elegante y mineral, un paso más en la colección",
    "wine-grape-63": "Tinto Fino — misma cuvée en magnum, ideal para compartir y con mejor evolución",
    "wine-grape-64": "Tinto Fino — de parcela única, expresivo y singular con gran potencial de guarda",
    "wine-grape-65": "Tinto Fino — el gran vino de Emilio Moro, sedoso y complejo con viñas viejas seleccionadas",
    "wine-grape-66": "Tempranillo, Cabernet Sauvignon, Syrah — fuera D.O., elegante y complejo del pago de Sardón",
    "wine-grape-67": "Tinto Fino — selección de autor de viñas viejas, potente y de gran personalidad",
    "wine-grape-68": "Tinto Fino — 3 años de crianza total, suave y elegante con final largo y notas de cedro",
    "wine-grape-69": "Tinto Fino — de Bodegas Valduero, selección de cepa única con gran estructura y elegancia",
    "wine-grape-70": "Tinto Fino — proyecto familiar de viñas centenarias, profundo e intenso",
    "wine-grape-71": "Tinto Fino — de Cillar de Silos, de viñas viejas de Gumiel de Mercado, complejo y sedoso",
    "wine-grape-72": "Tinto Fino, Cabernet Sauvignon, Merlot — uno de los grandes de la D.O., profundo y equilibrado",
    "wine-grape-73": "Tinto Fino — de parcelas seleccionadas, mineral y terroirista con gran precisión",
    "wine-grape-74": "Tinto Fino — la máxima expresión de Carmelo Rodero, selección de viñas viejas y gran añada",
    "wine-grape-75": "Tinto Fino — de viñas viejas, sedoso y elegante con fruta negra y especias nobles",
    "wine-grape-76": "Tinto Fino — reserva especial con larga crianza, elegante y complejo con final interminable",
    "wine-grape-77": "Tinto Fino — alta reserva de Valduero, larguísima crianza con una complejidad impresionante",
    "wine-grape-78": "Tinto Fino — de parcelas escogidas de Capellanes, elegante y con gran potencial de guarda",
    "wine-grape-79": "Tinto Fino — reserva de máxima expresión, largo envejecimiento y gran complejidad aromática",
    "wine-grape-80": "Tinto Fino — 5 años de crianza, uno de los grandes del Duero, sedoso y profundo",
    "wine-grape-81": "Tinto Fino — crianza 3 años en magnum para mayor evolución y expresión",
    "wine-grape-82": "Tinto Fino — finca singular, la máxima expresión de Francisco Barona, coleccionable",
    "wine-grape-83": "Tinto Fino — icono de Bodegas Montecastro, de viñas centenarias, potente y de guarda",
    "wine-grape-84": "Tinto Fino — Pago de Santa Cruz, icono de la bodega, profundo y con gran potencial de guarda",
    "wine-grape-85": "Tinto Fino — de viña única centenaria de Emilio Moro, uno de los grandes de España",
    "wine-grape-86": "Tinto Fino — gran reserva de Valduero, un referente de la D.O. con décadas de historia",
    "wine-grape-87": "Tinto Fino — gran reserva de larga crianza, complejo y evolucionado con gran elegancia",
    "wine-grape-88": "Tinto Fino — de parcela centenaria Rebollo, en magnum, el techo de la colección Postigo",
    "wine-grape-89": "Tinto Fino, Merlot — el hermano del mítico Vega Sicilia, 5 años de crianza y enorme complejidad",
    "wine-grape-90": "Tinto Fino — vinificación integral en roble, máxima expresión de la bodega en magnum",
    "wine-grape-91": "Tinto Fino — la máxima expresión de Pago de los Capellanes, preguntar disponibilidad",
    "wine-grape-92": "Tinta de Toro — joven y potente, con fruta oscura madura y el carácter robusto de la zona",
    "wine-grape-93": "Tinta de Toro — de Bodegas Tardencuba, estructurado y con personalidad, paso por roble",
    "wine-grape-94": "Malbec — variedad argentina implantada en Toro, potente y con notas de ciruela y violeta",
    "wine-grape-95": "Tinta de Toro — de Maurodos (Telmo Rodríguez), viñas viejas con carácter intenso y mineral",
    "wine-grape-96": "Tinta de Toro — de Bodegas Divina, potente y con gran concentración de fruta negra",
    "wine-grape-97": "Tinta de Toro — de Bodegas Latarce, potente y con fruta oscura madura y taninos maduros",
    "wine-grape-98": "Syrah — expresión mediterránea de esta variedad en Toro, especiada y con mucha fruta oscura",
    "wine-grape-99": "Tinta de Toro — de Vega Sicilia, la máxima expresión elegante del Toro, complejo y fino",
    "wine-grape-100": "Tinta de Toro — de Bodegas Frontio, vino de gran concentración y largo envejecimiento",
    "wine-grape-101": "Garnacha — variedad autóctona de la Sierra de Gredos, mineral y con fruta roja fresca",
    "wine-grape-102": "Tempranillo — reserva de Cigales, equilibrado y clásico con buena estructura",
    "wine-grape-103": "Tempranillo — de la zona de Cigales, potente y estructurado con notas de fruta madura",
    "wine-grape-104": "Syrah — de Bodegas Sommos en Aragón, intenso y especiado con gran concentración",
    "wine-grape-105": "Tempranillo, Garnacha — el icono fuera D.O. de Tudela del Duero, potente y complejo",
    "wine-grape-106": "Tempranillo, Garnacha — Vendimia Seleccionada de viñas viejas, un vino monumental",
    "wine-grape-107": "Tempranillo — de Mauro, el vino más exclusivo de la bodega, de viñas antiguas y gran guarda",
    "wine-grape-108": "Tempranillo — joven y frutal, vibrante y accesible con el sello de la Rioja Alavesa",
    "wine-grape-109": "Tempranillo, Garnacha — crianza riojana clásica y equilibrada de Bodegas Ondarre",
    "wine-grape-110": "Tempranillo — de parcelas seleccionadas con mayor expresión de terroir y complejidad",
    "wine-grape-111": "Tempranillo — de la Rioja Alavesa, fresco y mineral con taninos finos y buena acidez",
    "wine-grape-112": "Tempranillo, Mazuelo, Graciano — edición especial con mayor complejidad y personalidad",
    "wine-grape-113": "Tempranillo — de finca única Las Aguzaderas, el vino de autor de la bodega, mineral y profundo",
    "wine-grape-114": "Garnacha, Tempranillo, Mazuelo — de Palacios Remondo, garnacha riojana elegante y muy expresiva",
    "wine-grape-115": "Tempranillo, Graciano — clásico riojano moderno de Abel Mendoza, elegante y equilibrado",
    "wine-grape-116": "Tempranillo, Graciano — reserva elegante y evolucionada de una de las bodegas referentes",
    "wine-grape-117": "Tempranillo, Graciano, Mazuelo — reserva clásica de Bodegas Murua en la Rioja Alavesa",
    "wine-grape-118": "Tempranillo — selección especial de Beronia, con más carácter y largo envejecimiento en roble",
    "wine-grape-119": "Tempranillo — de parcela única de Amador Medrano, la cima de la bodega con gran expresión",
    "wine-grape-120": "Tempranillo — la cima de la colección Macán, vino de añadas especiales, preguntar disponibilidad",
    "wine-grape-121": "Tempranillo — versión más accesible de Macán, frutal y elegante, preguntar disponibilidad",
    "allergen-0": "Altramuces",
    "allergen-1": "Apio",
    "allergen-2": "Cacahuetes",
    "allergen-3": "Cereales con gluten",
    "allergen-4": "Crustáceos",
    "allergen-5": "Frutos secos",
    "allergen-6": "Huevos",
    "allergen-7": "Lácteos",
    "allergen-8": "Moluscos",
    "allergen-9": "Mostaza",
    "allergen-10": "Sésamo",
    "allergen-11": "Soja",
    "allergen-12": "Sulfitos",
    "allergen-13": "Pescado",
    "allergen-legend-title": "Referencia de Alérgenos"
  },
  "en": {
    "section-title-0": "Charcuterie Boards",
    "section-title-1": "Toasts",
    "section-title-2": "From the Farm",
    "section-title-3": "Fried Dishes",
    "section-title-4": "Keep Snacking…",
    "section-title-5": "Salads",
    "section-title-6": "From the Sea",
    "section-title-7": "From the Land",
    "section-title-8": "Vegan & Vegetarian",
    "section-title-9": "Sweet Farewell",
    "section-title-10": "Galician Whites",
    "section-title-11": "Galician Reds",
    "section-title-12": "Champagnes & Sparkling",
    "section-title-13": "Ribera del Duero",
    "section-title-14": "Toro",
    "section-title-15": "Castile & León",
    "section-title-16": "Riojas",
    "wine-subregion-0": "Monterrei",
    "wine-subregion-1": "Valdeorras",
    "wine-subregion-2": "Bierzo",
    "wine-subregion-3": "Albariños",
    "wine-subregion-4": "Ribeiros",
    "wine-subregion-5": "Godello",
    "wine-subregion-6": "Mencías & Galician Reds",
    "section-note-0": "With olive oil and balsamic vinegar",
    "section-note-1": "Main grape: Tempranillo (Tinto Fino) unless otherwise stated",
    "section-note-2": "Main grape: Tinta de Toro (local Tempranillo clone) unless otherwise stated",
    "section-note-3": "Main grape: Tempranillo unless otherwise stated",
    "item-name-0": "Iberian Ham",
    "item-name-1": "Iberian Ham",
    "item-name-2": "Iberian Board (Ham, chorizo, salchichón and loin)",
    "item-name-3": "Cheese Board (Tetilla, semi-cured, San Simón with almonds and quince)",
    "item-name-4": "Goat cheese roll, caramelized onion, bacon and walnuts, sweet chili sauce and balsamic",
    "item-name-5": "Tuna, confit piquillo peppers, pepper sauce and balsamic",
    "item-name-6": "Smoked salmon, fresh cheese, salad sprouts, pepper sauce and balsamic",
    "item-name-7": "Mallorcan sobrasada, brie, crispy onion, pepper sauce and balsamic",
    "item-name-8": "Anchovies, pepper jam, tetilla cheese and piquillo peppers",
    "item-name-9": "Mushrooms, ham and tomato with oil and parsley, pepper sauce and balsamic",
    "item-name-10": "Free-range eggs with ham and potatoes",
    "item-name-11": "Free-range eggs with small chorizos and potatoes",
    "item-name-12": "Free-range eggs with Iberian pork tenderloin, potatoes and mushroom sauce",
    "item-name-13": "Free-range eggs with Iberian secret cut, potatoes and ham",
    "item-name-14": "Scrambled eggs with mushrooms and king prawns",
    "item-name-15": "Scrambled eggs with cod and piquillo",
    "item-name-16": "Scrambled eggs with baby eels and prawns",
    "item-name-17": "Baby squid in corn flour batter with black garlic aioli",
    "item-name-18": "Homemade croquettes (ask for variety)",
    "item-name-19": "Crispy panko prawns with sweet and sour mayonnaise",
    "item-name-20": "Chicken wings with honey mustard sauce",
    "item-name-21": "Sautéed chicken dices, apple, teriyaki sauce, caramelized onion and potatoes",
    "item-name-22": "Spicy potatoes with aioli",
    "item-name-23": "Grilled baby cuttlefish, garlic and parsley oil and pepper aioli",
    "item-name-24": "Spanish omelette",
    "item-name-25": "Sautéed mushrooms and prawns",
    "item-name-26": "Cantabrian anchovies on grated tomato and oregano",
    "item-name-27": "Grilled Pacific scallops with garlic and parsley dressing",
    "item-name-28": "Little casserole of mushrooms and prawns in garlic",
    "item-name-29": "Tender leaves, piquillos, tuna belly and asparagus",
    "item-name-30": "Mixed leaves (with fried camembert and fig jam)",
    "item-name-31": "Ham, semi-cured cheese and nuts",
    "item-name-32": "Warm Atlantic scallops and prawns with nuts",
    "item-name-33": "Baked cod with mushrooms and chestnuts",
    "item-name-34": "Grilled cod with wok-sautéed vegetables",
    "item-name-35": "Grilled hake loin with seasonal salad",
    "item-name-36": "Grilled octopus tentacle",
    "item-name-37": "Grilled beef picanha",
    "item-name-38": "Grilled Galician veal entrecôte with pepper sauce",
    "item-name-39": "Iberian pork secreto with BBQ sauce",
    "item-name-40": "Aged beef T-bone (on request)",
    "item-name-41": "Mixed meats: Entrecôte, secreto and picanha (min. 2 people)",
    "item-name-42": "Ox burger with cheddar cheese, bacon and lettuce",
    "item-name-43": "Bread per person",
    "item-name-44": "Grilled vegetables (tomato, onion, peppers, courgette and mushrooms)",
    "item-name-45": "Sautéed vegetables (tomato, onion, peppers, courgette, aubergine, mushrooms, garlic and parsley)",
    "item-name-46": "Rice pudding",
    "item-name-47": "Chocolate lava cake with vanilla ice cream",
    "item-name-48": "Semi-cold cheesecake with strawberry jam",
    "item-name-49": "Tiramisu",
    "item-name-50": "Grandmother's cake",
    "item-name-51": "Coffee flan",
    "item-name-52": "Ladairo Godello",
    "item-name-53": "Crego Monaguillo",
    "item-name-54": "3 Mentiras",
    "item-name-55": "Godeval",
    "item-name-56": "O Luar do Sil",
    "item-name-57": "O Luar do Sil sobre Lías",
    "item-name-58": "Valtuille El Val",
    "item-name-59": "Mar de Nudos",
    "item-name-60": "Sentidiño",
    "item-name-61": "Goda",
    "item-name-62": "Gran Novas",
    "item-name-63": "Albamar Osebal",
    "item-name-64": "Davide",
    "item-name-65": "Viña Costeira Treixadura",
    "item-name-66": "Razamonde",
    "item-name-67": "Catro Ferrados",
    "item-name-68": "Valdesil Montenovo",
    "item-name-69": "Louro",
    "item-name-70": "La Llorona",
    "item-name-71": "Val de Sil 2023",
    "item-name-72": "Crego Monaguillo Monterrei",
    "item-name-73": "Ladairo Monterrei",
    "item-name-74": "3 Mentiras Monterrei",
    "item-name-75": "Fusco",
    "item-name-76": "Fulcro Alixe",
    "item-name-77": "Abeledos",
    "item-name-78": "Valtuille Bierzo",
    "item-name-79": "Pittacum Mencía",
    "item-name-80": "Cotarello Ribeiro (tinto)",
    "item-name-81": "AAA Tinto",
    "item-name-82": "Petalos del Bierzo",
    "item-name-83": "Attis Souson Rías Baixas",
    "item-name-84": "Heritage Blanc",
    "item-name-85": "Carramimbre Roble",
    "item-name-86": "Martín Berdugo Barrica",
    "item-name-87": "822",
    "item-name-88": "Coto Haya Centenario",
    "item-name-89": "Finca Resalso",
    "item-name-90": "Prios",
    "item-name-91": "Resalso Roble",
    "item-name-92": "Santa María",
    "item-name-93": "Tamaral Roble",
    "item-name-94": "Ceres",
    "item-name-95": "Valtravieso",
    "item-name-96": "Capellanes Roble",
    "item-name-97": "CLON 98",
    "item-name-98": "Ébano Salvaje",
    "item-name-99": "Viña Sastre",
    "item-name-100": "Carmelo Rodero 9 Meses",
    "item-name-101": "Tamaral Crianza",
    "item-name-102": "Martín Berdugo Crianza",
    "item-name-103": "Silvanus",
    "item-name-104": "Conde de San Cristóbal",
    "item-name-105": "La Cebolleta",
    "item-name-106": "Corimbo",
    "item-name-107": "Cair Finca Aguilera",
    "item-name-108": "Capellanes Crianza",
    "item-name-109": "Carmelo Rodero Crianza",
    "item-name-110": "Teófilo Reyes",
    "item-name-111": "Altamimbre",
    "item-name-112": "Convento San Francisco 2019",
    "item-name-113": "Arzuaga Crianza",
    "item-name-114": "La Felisa Emilio Moro",
    "item-name-115": "Cair Cuve Magnum",
    "item-name-116": "La Pinnaleta",
    "item-name-117": "Malleolus",
    "item-name-118": "Abadía Retuerta Selección Especial",
    "item-name-119": "Francisco Barona",
    "item-name-120": "Tomás Postigo 3 Año",
    "item-name-121": "Valduero I Cepa",
    "item-name-122": "A&M Asenjo Manso",
    "item-name-123": "Garmón 2019",
    "item-name-124": "Pago Carraovejas",
    "item-name-125": "Punto Geodésico",
    "item-name-126": "Raza Carmelo Rodero",
    "item-name-127": "Aalto",
    "item-name-128": "Dehesa Canónigos Solideo",
    "item-name-129": "Valduero Alta RVA",
    "item-name-130": "Un Sueño Pago de los Capellanes",
    "item-name-131": "Arzuaga Reserva Especial 2018",
    "item-name-132": "Tomás Postigo 5º Año",
    "item-name-133": "Tomás Postigo Magnum 3 Año",
    "item-name-134": "Francisco Barona Finca Las Dueñas",
    "item-name-135": "Sed de Caña",
    "item-name-136": "Aalto PS",
    "item-name-137": "Malleolus Valderramiro",
    "item-name-138": "Valduero Gran RVA",
    "item-name-139": "Luis Sanz Gran RVA",
    "item-name-140": "Tomás Postigo Rebollo Magnum",
    "item-name-141": "Valbuena 5º",
    "item-name-142": "Tomás Postigo Vinificación Integral Magnum",
    "item-name-143": "Doroteo Pago de los Capellanes",
    "item-name-144": "La Rejadora",
    "item-name-145": "Prima",
    "item-name-146": "Lorca Malbec",
    "item-name-147": "San Román",
    "item-name-148": "Platón Divina",
    "item-name-149": "Latarce",
    "item-name-150": "Syrah Matasnos",
    "item-name-151": "Pintia",
    "item-name-152": "Cartago",
    "item-name-153": "Alquez",
    "item-name-154": "Museum RVA",
    "item-name-155": "Albeniz Torre",
    "item-name-156": "Sommos Colección Syrah",
    "item-name-157": "Mauro",
    "item-name-158": "Mauro VS",
    "item-name-159": "Terreus",
    "item-name-160": "El Maquinista",
    "item-name-161": "Rioja Ondarre Crianza",
    "item-name-162": "Amador Medrano Los Sotillos",
    "item-name-163": "Bai Gorri",
    "item-name-164": "Beronia Edición Limitada",
    "item-name-165": "Amador Medrano Las Aguzaderas",
    "item-name-166": "La Montesa",
    "item-name-167": "Amaren",
    "item-name-168": "Luis Cañas Reserva 2018",
    "item-name-169": "Murua Rioja",
    "item-name-170": "Colección Privada Beronia",
    "item-name-171": "Los Sotillos",
    "item-name-172": "Macán Oro",
    "item-name-173": "Macán Clásico",
    "wine-grape-0": "Godello — elegant and unctuous, with vibrant acidity and citrus background",
    "wine-grape-1": "Godello — expressive, with aromas of stone fruit and almond notes at the end",
    "wine-grape-2": "Godello, Doña Blanca, Treixadura — fresh and mineral with notes of grass and white flower",
    "wine-grape-3": "Godello — reference of the D.O., clean and fresh with floral and mineral touches",
    "wine-grape-4": "Godello — spacious and elegant, with nuances of ripe fruit and slate mineral",
    "wine-grape-5": "Godello — aging on lees that provides creaminess, complexity and great persistence",
    "wine-grape-6": "Godello — unique estate in Bierzo, mineral and tense with perfect acidity",
    "wine-grape-7": "Albariño — starter wine that conveys the Atlantic character of the D.O. Rias Baixas",
    "wine-grape-8": "Albariño — fresh and aromatic, easy to drink with good value for money",
    "wine-grape-9": "Albariño — young and Atlantic, with citrus, peach and a touch of saline notes",
    "wine-grape-10": "Albariño — expressive and fruity, with good acidity and herbal background",
    "wine-grape-11": "Albariño — from O Salnés, very fruity, fresh and clean with a persistent finish",
    "wine-grape-12": "Albariño — elegant and complex, with aging that gives it depth and character",
    "wine-grape-13": "Treixadura — queen variety of Ribeiro, fresh and floral with a subtle and clean finish",
    "wine-grape-14": "Treixadura — from hillside vines, lively and mineral with a touch of aromatic grass",
    "wine-grape-15": "Treixadura, Godello, Albariño — coupage of native Ribeiro varieties with a lot of expression",
    "wine-grape-16": "Godello — young and direct, with the acidity and minerality characteristic of Valdeorras",
    "wine-grape-17": "Godello — barrel aging that provides complexity and elegant toasts",
    "wine-grape-18": "Godello — singular and signature, with a very marked Atlantic character and great freshness",
    "wine-grape-19": "Godello — from Valdeorras, expressive and tense with vibrant acidity and mineral finish",
    "wine-grape-20": "Mencía — fresh and fruity, with notes of cherry and violet typical of this Galician variety",
    "wine-grape-21": "Mencia — elegant and mineral, with soft tannins and a long, spicy finish",
    "wine-grape-22": "Mencia — juicy and accessible, with good red fruit and herbaceous terroir background",
    "wine-grape-23": "Mencia — young and sweet, with fresh fruit and soft tannins ideal for an aperitif",
    "wine-grape-24": "Mencía — from the Ribeira Sacra, mineral and vertical with the elegance of the granite terroir",
    "wine-grape-25": "Mencía — from vineyards on the slopes of the Ribeira Sacra, mineral and tense with concentrated fruit",
    "wine-grape-26": "Mencía — from Bierzo, floral and highly perfumed with silky tannins and vibrant acidity",
    "wine-grape-27": "Mencia — fresh aromas of red and violet fruit with elegant Bierzo tannins",
    "wine-grape-28": "Brancellao, Sousón, Ferrón — blend of native Ribeiro inks, unique and expressive",
    "wine-grape-29": "Mencía, Garnacha Tintorera — powerful and expressive blend with ripe black fruit",
    "wine-grape-30": "Mencía — by Álvaro Palacios, floral and elegant, considered a world reference for the variety",
    "wine-grape-31": "Sousón — recovered native Galician variety, intense and complex with great character",
    "wine-grape-32": "Chardonnay, Pinot Noir, Pinot Meunier — classically styled, fresh and balanced champagne",
    "wine-grape-33": "Tinto Fino — young with oak aging, accessible and fruity with well-integrated wood notes",
    "wine-grape-34": "Tinto Fino — smooth passage through the barrel, young and fruity with character typical of the Aranda area",
    "wine-grape-35": "Tinto Fino — starter wine from Bodegas Emilio Moro, fruity and easy to drink",
    "wine-grape-36": "Tinto Fino — from centuries-old vines, concentrated and deep with a lot of terroir personality",
    "wine-grape-37": "Tinto Fino — from Emilio Moro, from his own estate, young and concentrated with lots of red fruit",
    "wine-grape-38": "Tinto Fino — fresh and fruity from Bodegas Prios Maximus, with good value for money",
    "wine-grape-39": "Tinto Fino — from Emilio Moro, aged through oak with very lively and accessible fruit",
    "wine-grape-40": "Tinto Fino — from Convento San Francisco, young and accessible with notes of fresh fruit",
    "wine-grape-41": "Tinto Fino — passage through Bodegas Tamaral oak, fresh and fruity with a spicy touch",
    "wine-grape-42": "Tinto Fino — terroir, mineral and fresh wine with good natural acidity",
    "wine-grape-43": "Tinto Fino, Cabernet Sauvignon, Merlot — modern and fruity with an international presence",
    "wine-grape-44": "Tinto Fino — brief passage through oak, fruity and accessible, from one of the references of the D.O.",
    "wine-grape-45": "Tinto Fino — one of the oldest vintages of the D.O., with ripe fruit and good aging",
    "wine-grape-46": "Tinto Fino — from wild vines, wild and mineral character with great authenticity",
    "wine-grape-47": "Tinto Fino — from old vines in La Horra, elegant and terroirista with a lot of character",
    "wine-grape-48": "Tinto Fino — 9 months in barrel, powerful and spicy with a great personality",
    "wine-grape-49": "Tinto Fino — aged by Bodegas Tamaral, balanced and gastronomic with good structure",
    "wine-grape-50": "Tinto Fino — classic aging, balanced and very versatile to accompany meats and cheeses",
    "wine-grape-51": "Tinto Fino — from Bodegas Valduero, elegant and mineral with a great expression of the terroir",
    "wine-grape-52": "Tinto Fino, Cabernet Sauvignon, Merlot — modern and velvety with notes of black fruit and spices",
    "wine-grape-53": "Tinto Fino — from a century-old single vineyard, concentrated and terroirista with a lot of personality",
    "wine-grape-54": "Tinto Fino — from Bodegas Rivera, powerful and generous with ripe black fruit and well-integrated oak",
    "wine-grape-55": "Tinto Fino — from a unique, mineral and elegant estate aged in French oak",
    "wine-grape-56": "Tinto Fino — classic aging in American and French oak, balanced and very elegant",
    "wine-grape-57": "Tinto Fino, Cabernet Sauvignon — classic aging with a lot of structure and a long spicy finish",
    "wine-grape-58": "Tinto Fino — signature aging with long macerations, powerful and very expressive",
    "wine-grape-59": "Tinto Fino — expressive and concentrated, aged in French and American oak",
    "wine-grape-60": "Tinto Fino — older version, complex and mineral with a long finish in the mouth",
    "wine-grape-61": "Tinto Fino, Cabernet Sauvignon, Merlot — classic and balanced, with well-integrated tannins",
    "wine-grape-62": "Tinto Fino — from Emilio Moro's own estate, elegant and mineral, one more step in the collection",
    "wine-grape-63": "Tinto Fino — same cuvée in magnum, ideal for sharing and with better evolution",
    "wine-grape-64": "Tinto Fino — from a single plot, expressive and unique with great aging potential",
    "wine-grape-65": "Tinto Fino — Emilio Moro's great wine, silky and complex with selected old vines",
    "wine-grape-66": "Tempranillo, Cabernet Sauvignon, Syrah — outside D.O., elegant and complex from the Sardón region",
    "wine-grape-67": "Tinto Fino — author's selection of old vines, powerful and with great personality",
    "wine-grape-68": "Tinto Fino — 3 years of total aging, smooth and elegant with a long finish and notes of cedar",
    "wine-grape-69": "Tinto Fino — from Bodegas Valduero, selection of a unique strain with great structure and elegance",
    "wine-grape-70": "Tinto Fino — family project from centuries-old vines, deep and intense",
    "wine-grape-71": "Tinto Fino — from Cillar de Silos, from old Gumiel de Mercado vines, complex and silky",
    "wine-grape-72": "Tinto Fino, Cabernet Sauvignon, Merlot — one of the greats of the D.O., deep and balanced",
    "wine-grape-73": "Tinto Fino — from selected plots, mineral and terroiristic with great precision",
    "wine-grape-74": "Tinto Fino — the maximum expression of Carmelo Rodero, selection of old vines and great vintage",
    "wine-grape-75": "Tinto Fino — from old vines, silky and elegant with black fruit and noble spices",
    "wine-grape-76": "Tinto Fino — special reserve with long aging, elegant and complex with an endless finish",
    "wine-grape-77": "Tinto Fino — high reserve from Valduero, very long aging with impressive complexity",
    "wine-grape-78": "Tinto Fino — from selected plots of Capellanes, elegant and with great aging potential",
    "wine-grape-79": "Tinto Fino — reserve of maximum expression, long aging and great aromatic complexity",
    "wine-grape-80": "Tinto Fino — 5 years of aging, one of the greats of the Duero, silky and deep",
    "wine-grape-81": "Tinto Fino — aged 3 years in magnum for greater evolution and expression",
    "wine-grape-82": "Tinto Fino — unique estate, the maximum expression of Francisco Barona, collectible",
    "wine-grape-83": "Tinto Fino — icon of Bodegas Montecastro, with centuries-old vines, powerful and aged",
    "wine-grape-84": "Tinto Fino — Pago de Santa Cruz, icon of the winery, deep and with great aging potential",
    "wine-grape-85": "Tinto Fino — from a century-old single vineyard from Emilio Moro, one of the greats of Spain",
    "wine-grape-86": "Tinto Fino — great reserve from Valduero, a benchmark of the D.O. with decades of history",
    "wine-grape-87": "Tinto Fino — great reserve of long aging, complex and evolved with great elegance",
    "wine-grape-88": "Tinto Fino — from a century-old Rebollo plot, in magnum, the roof of the Postigo collection",
    "wine-grape-89": "Tinto Fino, Merlot — the brother of the legendary Vega Sicilia, 5 years of aging and enormous complexity",
    "wine-grape-90": "Tinto Fino — integral winemaking in oak, the maximum expression of the winery in magnum",
    "wine-grape-91": "Tinto Fino — the maximum expression of Pago de los Capellanes, ask for availability",
    "wine-grape-92": "Tinta de Toro — young and powerful, with ripe dark fruit and the robust character of the area",
    "wine-grape-93": "Tinta de Toro — from Bodegas Tardencuba, structured and with personality, aged in oak",
    "wine-grape-94": "Malbec — Argentine variety implanted in Toro, powerful and with notes of plum and violet",
    "wine-grape-95": "Tinta de Toro — from Maurodos (Telmo Rodríguez), old vines with intense and mineral character",
    "wine-grape-96": "Tinta de Toro — from Bodegas Divina, powerful and with a great concentration of black fruit",
    "wine-grape-97": "Tinta de Toro — from Bodegas Latarce, powerful and with ripe dark fruit and ripe tannins",
    "wine-grape-98": "Syrah — Mediterranean expression of this variety in Toro, spicy and with lots of dark fruit",
    "wine-grape-99": "Tinta de Toro — from Vega Sicilia, the maximum elegant expression of Toro, complex and fine",
    "wine-grape-100": "Tinta de Toro — from Bodegas Frontio, wine of great concentration and long aging",
    "wine-grape-101": "Garnacha — native variety from the Sierra de Gredos, mineral and with fresh red fruit",
    "wine-grape-102": "Tempranillo — Cigales reserve, balanced and classic with good structure",
    "wine-grape-103": "Tempranillo — from the Cigales area, powerful and structured with notes of ripe fruit",
    "wine-grape-104": "Syrah — from Bodegas Sommos in Aragón, intense and spicy with great concentration",
    "wine-grape-105": "Tempranillo, Garnacha — the icon outside D.O. from Tudela del Duero, powerful and complex",
    "wine-grape-106": "Tempranillo, Garnacha — Selected Harvest from old vines, a monumental wine",
    "wine-grape-107": "Tempranillo — from Mauro, the winery's most exclusive wine, from old vines and great aging",
    "wine-grape-108": "Tempranillo — young and fruity, vibrant and accessible with the seal of Rioja Alavesa",
    "wine-grape-109": "Tempranillo, Garnacha — classic and balanced Riojan aging from Bodegas Ondarre",
    "wine-grape-110": "Tempranillo — from selected plots with greater expression of terroir and complexity",
    "wine-grape-111": "Tempranillo — from Rioja Alavesa, fresh and mineral with fine tannins and good acidity",
    "wine-grape-112": "Tempranillo, Mazuelo, Graciano — special edition with greater complexity and personality",
    "wine-grape-113": "Tempranillo — from Las Aguzaderas single estate, the winery's signature wine, mineral and deep",
    "wine-grape-114": "Garnacha, Tempranillo, Mazuelo — from Palacios Remondo, elegant and very expressive Rioja Garnacha",
    "wine-grape-115": "Tempranillo, Graciano — Abel Mendoza's modern Riojan classic, elegant and balanced",
    "wine-grape-116": "Tempranillo, Graciano — elegant and evolved reserve from one of the leading wineries",
    "wine-grape-117": "Tempranillo, Graciano, Mazuelo — classic reserve of Bodegas Murua in Rioja Alavesa",
    "wine-grape-118": "Tempranillo — special selection from Beronia, with more character and long aging in oak",
    "wine-grape-119": "Tempranillo — from Amador Medrano's single plot, the top of the winery with great expression",
    "wine-grape-120": "Tempranillo — the top of the Macán collection, wine from special vintages, ask for availability",
    "wine-grape-121": "Tempranillo — more accessible version of Macán, fruity and elegant, ask for availability",
    "allergen-0": "Lupin",
    "allergen-1": "Celery",
    "allergen-2": "Peanuts",
    "allergen-3": "Gluten cereals",
    "allergen-4": "Crustaceans",
    "allergen-5": "Tree nuts",
    "allergen-6": "Eggs",
    "allergen-7": "Dairy",
    "allergen-8": "Molluscs",
    "allergen-9": "Mustard",
    "allergen-10": "Sesame",
    "allergen-11": "Soy",
    "allergen-12": "Sulphites",
    "allergen-13": "Fish",
    "allergen-legend-title": "Allergen Reference"
  },
  "fr": {
    "section-title-0": "Planches",
    "section-title-1": "Toasts",
    "section-title-2": "De la Ferme",
    "section-title-3": "Friture",
    "section-title-4": "On Continue à Grignoter…",
    "section-title-5": "Salades",
    "section-title-6": "De la Mer",
    "section-title-7": "De la Terre",
    "section-title-8": "Végétalien & Végétarien",
    "section-title-9": "Doux Au Revoir",
    "section-title-10": "Blancs de Galice",
    "section-title-11": "Rouges de Galice",
    "section-title-12": "Champagnes & Mousseux",
    "section-title-13": "Ribera del Duero",
    "section-title-14": "Toro",
    "section-title-15": "Castille et León",
    "section-title-16": "Riojas",
    "wine-subregion-0": "Monterrei",
    "wine-subregion-1": "Valdeorras",
    "wine-subregion-2": "Bierzo",
    "wine-subregion-3": "Albariños",
    "wine-subregion-4": "Ribeiros",
    "wine-subregion-5": "Godello",
    "wine-subregion-6": "Mencías & Rouges Galiciens",
    "section-note-0": "Avec huile d'olive et vinaigre balsamique",
    "section-note-1": "Cépage principal : Tempranillo (Tinto Fino) sauf indication contraire",
    "section-note-2": "Cépage principal : Tinta de Toro (clone local du Tempranillo) sauf indication contraire",
    "section-note-3": "Cépage principal : Tempranillo sauf indication contraire",
    "item-name-0": "Jambon Ibérique",
    "item-name-1": "Jambon Ibérique",
    "item-name-2": "Planche Ibérique (Jambon, chorizo, salchichón et longe)",
    "item-name-3": "Plateau de Fromages (Tetilla, demi-affiné, San Simón avec amandes et coing)",
    "item-name-4": "Rouleau de chèvre, oignon caramélisé, bacon et noix, sauce sweet chili et balsamique",
    "item-name-5": "Thon, poivrons piquillo confits, sauce poivron et balsamique",
    "item-name-6": "Saumon fumé, fromage frais, pousses de salade, sauce poivron et balsamique",
    "item-name-7": "Sobrasada majorquine, brie, oignon croustillant, sauce poivron et balsamique",
    "item-name-8": "Anchois, confiture de poivrons, fromage tetilla et poivrons piquillo",
    "item-name-9": "Champignons, jambon et tomate à l'huile et persil, sauce poivron et balsamique",
    "item-name-10": "Œufs fermiers avec jambon et pommes de terre",
    "item-name-11": "Œufs fermiers avec petits chorizos et pommes de terre",
    "item-name-12": "Œufs fermiers avec filet de porc ibérique, pommes de terre et sauce champignon",
    "item-name-13": "Œufs fermiers avec secreto ibérique, pommes de terre et jambon",
    "item-name-14": "Œufs brouillés aux champignons et gambas",
    "item-name-15": "Œufs brouillés à la morue et piquillo",
    "item-name-16": "Œufs brouillés aux gulas et crevettes",
    "item-name-17": "Calamars en friture de farine de maïs et aïoli d'ail noir",
    "item-name-18": "Croquettes maison (demander la variété)",
    "item-name-19": "Crevettes croustillantes en panko avec mayonnaise aigre-douce",
    "item-name-20": "Ailes de poulet à la sauce moutarde et miel",
    "item-name-21": "Dés de poulet sautés, pomme, sauce teriyaki, oignon caramélisé et pommes de terre",
    "item-name-22": "Pommes de terre bravas et aïoli",
    "item-name-23": "Petites seiches grillées, huile ail et persil et aïoli de poivrons",
    "item-name-24": "Omelette espagnole",
    "item-name-25": "Sauté de champignons et crevettes",
    "item-name-26": "Anchois du Cantabrique sur tomate râpée et origan",
    "item-name-27": "Pétoncles du Pacifique grillés à la vinaigrette ail et persil",
    "item-name-28": "Petite casserole de champignons et crevettes à l'ail",
    "item-name-29": "Feuilles tendres, piquillos, ventrèche de thon et asperges",
    "item-name-30": "Mélange de laitues (avec camembert frit et confiture de figues)",
    "item-name-31": "Jambon, fromage demi-affiné et fruits à coque",
    "item-name-32": "Tiède de pétoncles atlantiques et gambas aux fruits à coque",
    "item-name-33": "Morue au four aux champignons et châtaignes",
    "item-name-34": "Morue grillée avec légumes sautés au wok",
    "item-name-35": "Dos de merlu grillé avec salade de saison",
    "item-name-36": "Tentacule de poulpe grillé",
    "item-name-37": "Picanha de bœuf grillé",
    "item-name-38": "Entrecôte de veau galicien grillé avec sauce au poivre",
    "item-name-39": "Secreto de porc ibérique avec sauce BBQ",
    "item-name-40": "Côte de bœuf mature (sur commande)",
    "item-name-41": "Viandes variées : Entrecôte, secreto et picanha (min. 2 personnes)",
    "item-name-42": "Burger de bœuf avec cheddar, bacon et laitue",
    "item-name-43": "Pain par personne",
    "item-name-44": "Légumes grillés (tomate, oignon, poivrons, courgette et champignons)",
    "item-name-45": "Légumes sautés (tomate, oignon, poivrons, courgette, aubergine, champignons, ail et persil)",
    "item-name-46": "Riz au lait",
    "item-name-47": "Coulant au chocolat avec glace à la vanille",
    "item-name-48": "Tarte au fromage semi-froide avec confiture de fraises",
    "item-name-49": "Tiramisu",
    "item-name-50": "Tarte de la grand-mère",
    "item-name-51": "Flan au café",
    "item-name-52": "Ladairo Godello",
    "item-name-53": "Crego Monaguillo",
    "item-name-54": "3 Mentiras",
    "item-name-55": "Godeval",
    "item-name-56": "O Luar do Sil",
    "item-name-57": "O Luar do Sil sobre Lías",
    "item-name-58": "Valtuille El Val",
    "item-name-59": "Mar de Nudos",
    "item-name-60": "Sentidiño",
    "item-name-61": "Goda",
    "item-name-62": "Gran Novas",
    "item-name-63": "Albamar Osebal",
    "item-name-64": "Davide",
    "item-name-65": "Viña Costeira Treixadura",
    "item-name-66": "Razamonde",
    "item-name-67": "Catro Ferrados",
    "item-name-68": "Valdesil Montenovo",
    "item-name-69": "Louro",
    "item-name-70": "La Llorona",
    "item-name-71": "Val de Sil 2023",
    "item-name-72": "Crego Monaguillo Monterrei",
    "item-name-73": "Ladairo Monterrei",
    "item-name-74": "3 Mentiras Monterrei",
    "item-name-75": "Fusco",
    "item-name-76": "Fulcro Alixe",
    "item-name-77": "Abeledos",
    "item-name-78": "Valtuille Bierzo",
    "item-name-79": "Pittacum Mencía",
    "item-name-80": "Cotarello Ribeiro (tinto)",
    "item-name-81": "AAA Tinto",
    "item-name-82": "Petalos del Bierzo",
    "item-name-83": "Attis Souson Rías Baixas",
    "item-name-84": "Heritage Blanc",
    "item-name-85": "Carramimbre Roble",
    "item-name-86": "Martín Berdugo Barrica",
    "item-name-87": "822",
    "item-name-88": "Coto Haya Centenario",
    "item-name-89": "Finca Resalso",
    "item-name-90": "Prios",
    "item-name-91": "Resalso Roble",
    "item-name-92": "Santa María",
    "item-name-93": "Tamaral Roble",
    "item-name-94": "Ceres",
    "item-name-95": "Valtravieso",
    "item-name-96": "Capellanes Roble",
    "item-name-97": "CLON 98",
    "item-name-98": "Ébano Salvaje",
    "item-name-99": "Viña Sastre",
    "item-name-100": "Carmelo Rodero 9 Meses",
    "item-name-101": "Tamaral Crianza",
    "item-name-102": "Martín Berdugo Crianza",
    "item-name-103": "Silvanus",
    "item-name-104": "Conde de San Cristóbal",
    "item-name-105": "La Cebolleta",
    "item-name-106": "Corimbo",
    "item-name-107": "Cair Finca Aguilera",
    "item-name-108": "Capellanes Crianza",
    "item-name-109": "Carmelo Rodero Crianza",
    "item-name-110": "Teófilo Reyes",
    "item-name-111": "Altamimbre",
    "item-name-112": "Convento San Francisco 2019",
    "item-name-113": "Arzuaga Crianza",
    "item-name-114": "La Felisa Emilio Moro",
    "item-name-115": "Cair Cuve Magnum",
    "item-name-116": "La Pinnaleta",
    "item-name-117": "Malleolus",
    "item-name-118": "Abadía Retuerta Selección Especial",
    "item-name-119": "Francisco Barona",
    "item-name-120": "Tomás Postigo 3 Año",
    "item-name-121": "Valduero I Cepa",
    "item-name-122": "A&M Asenjo Manso",
    "item-name-123": "Garmón 2019",
    "item-name-124": "Pago Carraovejas",
    "item-name-125": "Punto Geodésico",
    "item-name-126": "Raza Carmelo Rodero",
    "item-name-127": "Aalto",
    "item-name-128": "Dehesa Canónigos Solideo",
    "item-name-129": "Valduero Alta RVA",
    "item-name-130": "Un Sueño Pago de los Capellanes",
    "item-name-131": "Arzuaga Reserva Especial 2018",
    "item-name-132": "Tomás Postigo 5º Año",
    "item-name-133": "Tomás Postigo Magnum 3 Año",
    "item-name-134": "Francisco Barona Finca Las Dueñas",
    "item-name-135": "Sed de Caña",
    "item-name-136": "Aalto PS",
    "item-name-137": "Malleolus Valderramiro",
    "item-name-138": "Valduero Gran RVA",
    "item-name-139": "Luis Sanz Gran RVA",
    "item-name-140": "Tomás Postigo Rebollo Magnum",
    "item-name-141": "Valbuena 5º",
    "item-name-142": "Tomás Postigo Vinificación Integral Magnum",
    "item-name-143": "Doroteo Pago de los Capellanes",
    "item-name-144": "La Rejadora",
    "item-name-145": "Prima",
    "item-name-146": "Lorca Malbec",
    "item-name-147": "San Román",
    "item-name-148": "Platón Divina",
    "item-name-149": "Latarce",
    "item-name-150": "Syrah Matasnos",
    "item-name-151": "Pintia",
    "item-name-152": "Cartago",
    "item-name-153": "Alquez",
    "item-name-154": "Museum RVA",
    "item-name-155": "Albeniz Torre",
    "item-name-156": "Sommos Colección Syrah",
    "item-name-157": "Mauro",
    "item-name-158": "Mauro VS",
    "item-name-159": "Terreus",
    "item-name-160": "El Maquinista",
    "item-name-161": "Rioja Ondarre Crianza",
    "item-name-162": "Amador Medrano Los Sotillos",
    "item-name-163": "Bai Gorri",
    "item-name-164": "Beronia Edición Limitada",
    "item-name-165": "Amador Medrano Las Aguzaderas",
    "item-name-166": "La Montesa",
    "item-name-167": "Amaren",
    "item-name-168": "Luis Cañas Reserva 2018",
    "item-name-169": "Murua Rioja",
    "item-name-170": "Colección Privada Beronia",
    "item-name-171": "Los Sotillos",
    "item-name-172": "Macán Oro",
    "item-name-173": "Macán Clásico",
    "wine-grape-0": "Godello — élégant et onctueux, avec une acidité vibrante et un fond d'agrumes",
    "wine-grape-1": "Godello — expressif, avec des arômes de fruits à noyau et des notes d'amande à la fin",
    "wine-grape-2": "Godello, Doña Blanca, Treixadura — frais et minéraux avec des notes d'herbe et de fleur blanche",
    "wine-grape-3": "Godello — référence de la D.O., propre et frais avec des touches florales et minérales",
    "wine-grape-4": "Godello — spacieux et élégant, avec des nuances de fruits mûrs et de minéraux d'ardoise",
    "wine-grape-5": "Godello - élevage sur lies qui apporte onctuosité, complexité et grande persistance",
    "wine-grape-6": "Godello — domaine unique dans le Bierzo, minéral et tendu avec une acidité parfaite",
    "wine-grape-7": "Albariño — vin de départ qui transmet le caractère atlantique de la D.O. Rías Baixas",
    "wine-grape-8": "Albariño — frais et aromatique, facile à boire avec un bon rapport qualité-prix",
    "wine-grape-9": "Albariño — jeune et atlantique, avec des agrumes, de la pêche et une touche de notes salines",
    "wine-grape-10": "Albariño — expressif et fruité, avec une bonne acidité et un fond herbacé",
    "wine-grape-11": "Albariño — d'O Salnés, très fruité, frais et net avec une finale persistante",
    "wine-grape-12": "Albariño — élégant et complexe, avec un vieillissement qui lui donne profondeur et caractère",
    "wine-grape-13": "Treixadura — variété reine du Ribeiro, fraîche et florale avec une finale subtile et nette",
    "wine-grape-14": "Treixadura — issue de vignes à flanc de coteau, vive et minérale avec une touche d'herbe aromatique",
    "wine-grape-15": "Treixadura, Godello, Albariño — coupage de variétés indigènes Ribeiro avec beaucoup d'expression",
    "wine-grape-16": "Godello — jeune et direct, avec l'acidité et la minéralité caractéristiques de Valdeorras",
    "wine-grape-17": "Godello – un élevage en barrique qui apporte complexité et élégance aux toasts",
    "wine-grape-18": "Godello — singulier et signature, avec un caractère atlantique très marqué et une grande fraîcheur",
    "wine-grape-19": "Godello — de Valdeorras, expressif et tendu avec une acidité vibrante et une finale minérale",
    "wine-grape-20": "Mencía — fraîche et fruitée, avec des notes de cerise et de violette typiques de cette variété galicienne",
    "wine-grape-21": "Mencia — élégante et minérale, avec des tanins souples et une finale longue et épicée",
    "wine-grape-22": "Mencia — juteuse et accessible, avec de bons fruits rouges et un fond de terroir herbacé",
    "wine-grape-23": "Mencia — jeune et douce, avec des fruits frais et des tanins souples, idéale pour un apéritif",
    "wine-grape-24": "Mencía — de la Ribeira Sacra, minérale et verticale avec l'élégance du terroir granitique",
    "wine-grape-25": "Mencía — issue de vignobles sur les pentes de la Ribeira Sacra, minérale et tendue avec un fruit concentré",
    "wine-grape-26": "Mencía — du Bierzo, florale et très parfumée avec des tanins soyeux et une acidité vibrante",
    "wine-grape-27": "Mencia — arômes frais de fruits rouges et violets avec des tanins élégants de Bierzo",
    "wine-grape-28": "Brancellao, Sousón, Ferrón — mélange d'encres indigènes Ribeiro, unique et expressif",
    "wine-grape-29": "Mencía, Garnacha Tintorera — mélange puissant et expressif aux fruits noirs mûrs",
    "wine-grape-30": "Mencía — d'Álvaro Palacios, florale et élégante, considérée comme une référence mondiale pour cette variété",
    "wine-grape-31": "Sousón — variété indigène galicienne récupérée, intense et complexe avec beaucoup de caractère",
    "wine-grape-32": "Chardonnay, Pinot Noir, Pinot Meunier — champagne de style classique, frais et équilibré",
    "wine-grape-33": "Tinto Fino — jeune avec un vieillissement en chêne, accessible et fruité avec des notes boisées bien intégrées",
    "wine-grape-34": "Tinto Fino — passage en barrique doux, jeune et fruité avec un caractère typique de la région d'Aranda",
    "wine-grape-35": "Tinto Fino — vin d'entrée de Bodegas Emilio Moro, fruité et facile à boire",
    "wine-grape-36": "Tinto Fino — issu de vignes centenaires, concentré et profond avec beaucoup de personnalité du terroir",
    "wine-grape-37": "Tinto Fino — d'Emilio Moro, de son propre domaine, jeune et concentré avec beaucoup de fruits rouges",
    "wine-grape-38": "Tinto Fino — frais et fruité de Bodegas Prios Maximus, avec un bon rapport qualité-prix",
    "wine-grape-39": "Tinto Fino — d'Emilio Moro, vieilli en chêne avec un fruit très vif et accessible",
    "wine-grape-40": "Tinto Fino — du Convento San Francisco, jeune et accessible avec des notes de fruits frais",
    "wine-grape-41": "Tinto Fino — passage par le chêne Bodegas Tamaral, frais et fruité avec une touche épicée",
    "wine-grape-42": "Tinto Fino — vin de terroir, minéral et frais avec une bonne acidité naturelle",
    "wine-grape-43": "Tinto Fino, Cabernet Sauvignon, Merlot — modernes et fruités avec une présence internationale",
    "wine-grape-44": "Tinto Fino — bref passage en chêne, fruité et accessible, d'une des références de la D.O.",
    "wine-grape-45": "Tinto Fino — un des plus anciens millésimes de la D.O., avec des fruits mûrs et un bon vieillissement",
    "wine-grape-46": "Tinto Fino — issu de vignes sauvages, caractère sauvage et minéral avec une grande authenticité",
    "wine-grape-47": "Tinto Fino — issu de vieilles vignes de La Horra, élégant et terroiriste avec beaucoup de caractère",
    "wine-grape-48": "Tinto Fino — 9 mois en fût, puissant et épicé avec une grande personnalité",
    "wine-grape-49": "Tinto Fino — vieilli par Bodegas Tamaral, équilibré et gastronomique avec une bonne structure",
    "wine-grape-50": "Tinto Fino — vieillissement classique, équilibré et très polyvalent pour accompagner les viandes et les fromages",
    "wine-grape-51": "Tinto Fino — de Bodegas Valduero, élégant et minéral avec une grande expression du terroir",
    "wine-grape-52": "Tinto Fino, Cabernet Sauvignon, Merlot — moderne et velouté avec des notes de fruits noirs et d'épices",
    "wine-grape-53": "Tinto Fino — issu d'un vignoble unique centenaire, concentré et terroiriste avec beaucoup de personnalité",
    "wine-grape-54": "Tinto Fino — de Bodegas Rivera, puissant et généreux avec des fruits noirs mûrs et un chêne bien intégré",
    "wine-grape-55": "Tinto Fino — issu d'un domaine unique, minéral et élégant élevé en chêne français",
    "wine-grape-56": "Tinto Fino — élevage classique en chêne américain et français, équilibré et très élégant",
    "wine-grape-57": "Tinto Fino, Cabernet Sauvignon — élevage classique avec beaucoup de structure et une longue finale épicée",
    "wine-grape-58": "Tinto Fino — élevage signature avec de longues macérations, puissant et très expressif",
    "wine-grape-59": "Tinto Fino — expressif et concentré, vieilli en chêne français et américain",
    "wine-grape-60": "Tinto Fino — version plus ancienne, complexe et minérale avec une longue finale en bouche",
    "wine-grape-61": "Tinto Fino, Cabernet Sauvignon, Merlot — classiques et équilibrés, avec des tanins bien intégrés",
    "wine-grape-62": "Tinto Fino — de la propriété d'Emilio Moro, élégant et minéral, une étape de plus dans la collection",
    "wine-grape-63": "Tinto Fino — même cuvée en magnum, idéale pour le partage et avec une meilleure évolution",
    "wine-grape-64": "Tinto Fino — issu d'une seule parcelle, expressif et unique avec un grand potentiel de garde",
    "wine-grape-65": "Tinto Fino — Le grand vin d'Emilio Moro, soyeux et complexe avec de vieilles vignes sélectionnées",
    "wine-grape-66": "Tempranillo, Cabernet Sauvignon, Syrah — hors D.O., élégant et complexe de la région de Sardón",
    "wine-grape-67": "Tinto Fino — sélection d'auteur de vieilles vignes, puissantes et avec une grande personnalité",
    "wine-grape-68": "Tinto Fino — 3 ans de vieillissement total, doux et élégant avec une longue finale et des notes de cèdre",
    "wine-grape-69": "Tinto Fino — de Bodegas Valduero, sélection d'une variété unique avec une grande structure et élégance",
    "wine-grape-70": "Tinto Fino — projet familial issu de vignes centenaires, profond et intense",
    "wine-grape-71": "Tinto Fino — de Cillar de Silos, issu de vieilles vignes de Gumiel de Mercado, complexe et soyeux",
    "wine-grape-72": "Tinto Fino, Cabernet Sauvignon, Merlot — un des grands de la D.O., profond et équilibré",
    "wine-grape-73": "Tinto Fino — issu de parcelles sélectionnées, minérales et terroiristes avec une grande précision",
    "wine-grape-74": "Tinto Fino — l'expression maximale de Carmelo Rodero, sélection de vieilles vignes et de grands millésimes",
    "wine-grape-75": "Tinto Fino — issu de vieilles vignes, soyeux et élégant aux fruits noirs et épices nobles",
    "wine-grape-76": "Tinto Fino — réserve spéciale de longue garde, élégante et complexe avec une finale sans fin",
    "wine-grape-77": "Tinto Fino — grande réserve de Valduero, très long vieillissement et complexité impressionnante",
    "wine-grape-78": "Tinto Fino — issu de parcelles sélectionnées de Capellanes, élégant et avec un grand potentiel de garde",
    "wine-grape-79": "Tinto Fino — réserve d'expression maximale, long vieillissement et grande complexité aromatique",
    "wine-grape-80": "Tinto Fino — 5 ans de garde, l'un des grands du Duero, soyeux et profond",
    "wine-grape-81": "Tinto Fino — vieilli 3 ans en magnum pour plus d'évolution et d'expression",
    "wine-grape-82": "Tinto Fino — domaine unique, expression maximale de Francisco Barona, objet de collection",
    "wine-grape-83": "Tinto Fino — icône des Bodegas Montecastro, aux vignes centenaires, puissantes et âgées",
    "wine-grape-84": "Tinto Fino — Pago de Santa Cruz, icône de la cave, profond et avec un grand potentiel de garde",
    "wine-grape-85": "Tinto Fino — issu d'un seul vignoble centenaire d'Emilio Moro, l'un des plus grands d'Espagne",
    "wine-grape-86": "Tinto Fino — grande réserve de Valduero, une référence de la D.O. avec des décennies d'histoire",
    "wine-grape-87": "Tinto Fino — grande réserve de longue garde, complexe et évolué avec une grande élégance",
    "wine-grape-88": "Tinto Fino — d'une parcelle Rebollo centenaire, en magnum, le toit de la collection Postigo",
    "wine-grape-89": "Tinto Fino, Merlot — le frère du légendaire Vega Sicilia, 5 ans de vieillissement et une énorme complexité",
    "wine-grape-90": "Tinto Fino — vinification intégrale en chêne, l'expression maximale de la cave en magnum",
    "wine-grape-91": "Tinto Fino — l'expression maximale du Pago de los Capellanes, demandez la disponibilité",
    "wine-grape-92": "Tinta de Toro — jeune et puissante, avec des fruits noirs mûrs et le caractère robuste de la région",
    "wine-grape-93": "Tinta de Toro — de Bodegas Tardencuba, structurée et pleine de personnalité, vieillie en chêne",
    "wine-grape-94": "Malbec — Variété argentine implantée à Toro, puissante et aux notes de prune et de violette",
    "wine-grape-95": "Tinta de Toro — de Maurodos (Telmo Rodríguez), vieilles vignes au caractère intense et minéral",
    "wine-grape-96": "Tinta de Toro — de Bodegas Divina, puissante et avec une grande concentration de fruits noirs",
    "wine-grape-97": "Tinta de Toro — de Bodegas Latarce, puissante et avec des fruits noirs mûrs et des tanins mûrs",
    "wine-grape-98": "Syrah — Expression méditerranéenne de ce cépage en Toro, épicée et avec beaucoup de fruits noirs",
    "wine-grape-99": "Tinta de Toro — de Vega Sicilia, l'expression la plus élégante du Toro, complexe et fine",
    "wine-grape-100": "Tinta de Toro — de Bodegas Frontio, vin de grande concentration et de longue garde",
    "wine-grape-101": "Garnacha — variété indigène de la Sierra de Gredos, minérale et aux fruits rouges frais",
    "wine-grape-102": "Tempranillo — Réserve de Cigales, équilibrée et classique avec une bonne structure",
    "wine-grape-103": "Tempranillo — de la région des Cigales, puissant et structuré avec des notes de fruits mûrs",
    "wine-grape-104": "Syrah — de Bodegas Sommos en Aragon, intense et épicée avec une grande concentration",
    "wine-grape-105": "Tempranillo, Garnacha - l'icône en dehors de la D.O. de Tudela del Duero, puissant et complexe",
    "wine-grape-106": "Tempranillo, Garnacha — Vendanges sélectionnées de vieilles vignes, un vin monumental",
    "wine-grape-107": "Tempranillo — de Mauro, le vin le plus exclusif de la cave, issu de vieilles vignes et d'un grand vieillissement",
    "wine-grape-108": "Tempranillo — jeune et fruité, vibrant et accessible avec le sceau de la Rioja Alavesa",
    "wine-grape-109": "Tempranillo, Garnacha — vieillissement riojan classique et équilibré de Bodegas Ondarre",
    "wine-grape-110": "Tempranillo — issu de parcelles sélectionnées avec une plus grande expression du terroir et de la complexité",
    "wine-grape-111": "Tempranillo — de la Rioja Alavesa, frais et minéral avec des tanins fins et une bonne acidité",
    "wine-grape-112": "Tempranillo, Mazuelo, Graciano — édition spéciale avec plus de complexité et de personnalité",
    "wine-grape-113": "Tempranillo — du domaine unique de Las Aguzaderas, le vin signature de la cave, minéral et profond",
    "wine-grape-114": "Garnacha, Tempranillo, Mazuelo — de Palacios Remondo, Rioja Garnacha élégant et très expressif",
    "wine-grape-115": "Tempranillo, Graciano — Le classique moderne de la Rioja d'Abel Mendoza, élégant et équilibré",
    "wine-grape-116": "Tempranillo, Graciano — réserve élégante et évoluée de l'un des principaux vignobles",
    "wine-grape-117": "Tempranillo, Graciano, Mazuelo — réserve classique des Bodegas Murua dans la Rioja Alavesa",
    "wine-grape-118": "Tempranillo — sélection spéciale de Beronia, avec plus de caractère et un long vieillissement en fûts de chêne",
    "wine-grape-119": "Tempranillo — de la parcelle unique d'Amador Medrano, le sommet de la cave avec une grande expression",
    "wine-grape-120": "Tempranillo — le haut de la collection Macán, vin de millésimes spéciaux, demandez la disponibilité",
    "wine-grape-121": "Tempranillo — version plus accessible du Macán, fruitée et élégante, demandez disponibilité",
    "allergen-0": "Lupin",
    "allergen-1": "Céleri",
    "allergen-2": "Cacahuètes",
    "allergen-3": "Céréales gluten",
    "allergen-4": "Crustacés",
    "allergen-5": "Fruits à coque",
    "allergen-6": "Œufs",
    "allergen-7": "Laitiers",
    "allergen-8": "Mollusques",
    "allergen-9": "Moutarde",
    "allergen-10": "Sésame",
    "allergen-11": "Soja",
    "allergen-12": "Sulfites",
    "allergen-13": "Poisson",
    "allergen-legend-title": "Référence des Allergènes"
  },
  "de": {
    "section-title-0": "Bretter",
    "section-title-1": "Toasts",
    "section-title-2": "Vom Hof",
    "section-title-3": "Gebratenes",
    "section-title-4": "Weiter Snacken…",
    "section-title-5": "Salate",
    "section-title-6": "Vom Meer",
    "section-title-7": "Vom Land",
    "section-title-8": "Vegan & Vegetarisch",
    "section-title-9": "Süßer Abschluss",
    "section-title-10": "Galicische Weißweine",
    "section-title-11": "Galicische Rotweine",
    "section-title-12": "Champagner & Schaumweine",
    "section-title-13": "Ribera del Duero",
    "section-title-14": "Toro",
    "section-title-15": "Kastilien und León",
    "section-title-16": "Riojas",
    "wine-subregion-0": "Monterrei",
    "wine-subregion-1": "Valdeorras",
    "wine-subregion-2": "Bierzo",
    "wine-subregion-3": "Albariños",
    "wine-subregion-4": "Ribeiros",
    "wine-subregion-5": "Godello",
    "wine-subregion-6": "Mencías & Galicische Rotweine",
    "section-note-0": "Mit Olivenöl und Balsamico-Essig",
    "section-note-1": "Haupttraube: Tempranillo (Tinto Fino) sofern nicht anders angegeben",
    "section-note-2": "Haupttraube: Tinta de Toro (lokaler Tempranillo-Klon) sofern nicht anders angegeben",
    "section-note-3": "Haupttraube: Tempranillo sofern nicht anders angegeben",
    "item-name-0": "Iberischer Schinken",
    "item-name-1": "Iberischer Schinken",
    "item-name-2": "Iberische Platte (Schinken, Chorizo, Salchichón und Lende)",
    "item-name-3": "Käseplatte (Tetilla, halbgereift, San Simón mit Mandeln und Quitte)",
    "item-name-4": "Ziegenkäserolle, karamellisierte Zwiebeln, Speck und Nüsse, Sweet-Chili-Sauce und Balsamico",
    "item-name-5": "Thunfisch, confierte Piquillo-Paprika, Paprikasauce und Balsamico",
    "item-name-6": "Räucherlachs, Frischkäse, Salatsprossen, Paprikasauce und Balsamico",
    "item-name-7": "Mallorquinische Sobrasada, Brie, knusprige Zwiebeln, Paprikasauce und Balsamico",
    "item-name-8": "Sardellen, Paprikamarmelade, Tetilla-Käse und Piquillo-Paprika",
    "item-name-9": "Pilze, Schinken und Tomate mit Öl und Petersilie, Paprikasauce und Balsamico",
    "item-name-10": "Freilandeier mit Schinken und Kartoffeln",
    "item-name-11": "Freilandeier mit kleinen Chorizos und Kartoffeln",
    "item-name-12": "Freilandeier mit iberischem Schweinefilet, Kartoffeln und Pilzsauce",
    "item-name-13": "Freilandeier mit iberischem Secreto, Kartoffeln und Schinken",
    "item-name-14": "Rührei mit Pilzen und Riesengarnelen",
    "item-name-15": "Rührei mit Kabeljau und Piquillo",
    "item-name-16": "Rührei mit Babyaalen und Garnelen",
    "item-name-17": "Baby-Tintenfisch in Maismehlteig mit Schwarzknoblauch-Aioli",
    "item-name-18": "Hausgemachte Kroketten (Sorte erfragen)",
    "item-name-19": "Knusprige Panko-Garnelen mit Süß-Sauer-Mayonnaise",
    "item-name-20": "Hühnerflügel mit Honig-Senf-Sauce",
    "item-name-21": "Gebratene Hühnerwürfel, Apfel, Teriyaki-Sauce, karamellisierte Zwiebeln und Kartoffeln",
    "item-name-22": "Bravas-Kartoffeln mit Aioli",
    "item-name-23": "Gegrillte Baby-Tintenfische, Knoblauch-Petersilienöl und Paprika-Aioli",
    "item-name-24": "Spanisches Omelett",
    "item-name-25": "Gebratene Pilze und Garnelen",
    "item-name-26": "Kantabrische Sardellen auf geriebenem Tomaten und Oregano",
    "item-name-27": "Gegrillte Pazifik-Jakobsmuscheln mit Knoblauch-Petersilien-Dressing",
    "item-name-28": "Kleiner Topf mit Pilzen und Garnelen in Knoblauch",
    "item-name-29": "Zarte Blätter, Piquillo-Paprika, Thunbauch und Spargel",
    "item-name-30": "Gemischte Blätter (mit gebratenem Camembert und Feigenmarmelade)",
    "item-name-31": "Schinken, halbgereifter Käse und Nüsse",
    "item-name-32": "Warme Atlantik-Jakobsmuscheln und Garnelen mit Nüssen",
    "item-name-33": "Gebackener Kabeljau mit Pilzen und Kastanien",
    "item-name-34": "Gegrillter Kabeljau mit Wok-Gemüse",
    "item-name-35": "Gegrilltes Seehecht-Lende mit Saisonsalat",
    "item-name-36": "Gegrillter Oktopus-Tentakel",
    "item-name-37": "Gegrilltes Rinder-Picanha",
    "item-name-38": "Gegrilltes galicisches Kalbsentrecôte mit Pfeffersauce",
    "item-name-39": "Iberisches Schweine-Secreto mit BBQ-Sauce",
    "item-name-40": "Gereiftes Rinder-T-Bone (auf Bestellung)",
    "item-name-41": "Gemischtes Fleisch: Entrecôte, Secreto und Picanha (mind. 2 Personen)",
    "item-name-42": "Ochsenburger mit Cheddar, Speck und Salat",
    "item-name-43": "Brot pro Person",
    "item-name-44": "Gegrilltes Gemüse (Tomate, Zwiebel, Paprika, Zucchini und Pilze)",
    "item-name-45": "Gebratenes Gemüse (Tomate, Zwiebel, Paprika, Zucchini, Aubergine, Pilze, Knoblauch und Petersilie)",
    "item-name-46": "Milchreis",
    "item-name-47": "Schokoladen-Lava-Kuchen mit Vanilleeis",
    "item-name-48": "Halbgefrorene Käsekuchen mit Erdbeermarmelade",
    "item-name-49": "Tiramisu",
    "item-name-50": "Omas Kuchen",
    "item-name-51": "Kaffeeflan",
    "item-name-52": "Ladairo Godello",
    "item-name-53": "Crego Monaguillo",
    "item-name-54": "3 Mentiras",
    "item-name-55": "Godeval",
    "item-name-56": "O Luar do Sil",
    "item-name-57": "O Luar do Sil sobre Lías",
    "item-name-58": "Valtuille El Val",
    "item-name-59": "Mar de Nudos",
    "item-name-60": "Sentidiño",
    "item-name-61": "Goda",
    "item-name-62": "Gran Novas",
    "item-name-63": "Albamar Osebal",
    "item-name-64": "Davide",
    "item-name-65": "Viña Costeira Treixadura",
    "item-name-66": "Razamonde",
    "item-name-67": "Catro Ferrados",
    "item-name-68": "Valdesil Montenovo",
    "item-name-69": "Louro",
    "item-name-70": "La Llorona",
    "item-name-71": "Val de Sil 2023",
    "item-name-72": "Crego Monaguillo Monterrei",
    "item-name-73": "Ladairo Monterrei",
    "item-name-74": "3 Mentiras Monterrei",
    "item-name-75": "Fusco",
    "item-name-76": "Fulcro Alixe",
    "item-name-77": "Abeledos",
    "item-name-78": "Valtuille Bierzo",
    "item-name-79": "Pittacum Mencía",
    "item-name-80": "Cotarello Ribeiro (tinto)",
    "item-name-81": "AAA Tinto",
    "item-name-82": "Petalos del Bierzo",
    "item-name-83": "Attis Souson Rías Baixas",
    "item-name-84": "Heritage Blanc",
    "item-name-85": "Carramimbre Roble",
    "item-name-86": "Martín Berdugo Barrica",
    "item-name-87": "822",
    "item-name-88": "Coto Haya Centenario",
    "item-name-89": "Finca Resalso",
    "item-name-90": "Prios",
    "item-name-91": "Resalso Roble",
    "item-name-92": "Santa María",
    "item-name-93": "Tamaral Roble",
    "item-name-94": "Ceres",
    "item-name-95": "Valtravieso",
    "item-name-96": "Capellanes Roble",
    "item-name-97": "CLON 98",
    "item-name-98": "Ébano Salvaje",
    "item-name-99": "Viña Sastre",
    "item-name-100": "Carmelo Rodero 9 Meses",
    "item-name-101": "Tamaral Crianza",
    "item-name-102": "Martín Berdugo Crianza",
    "item-name-103": "Silvanus",
    "item-name-104": "Conde de San Cristóbal",
    "item-name-105": "La Cebolleta",
    "item-name-106": "Corimbo",
    "item-name-107": "Cair Finca Aguilera",
    "item-name-108": "Capellanes Crianza",
    "item-name-109": "Carmelo Rodero Crianza",
    "item-name-110": "Teófilo Reyes",
    "item-name-111": "Altamimbre",
    "item-name-112": "Convento San Francisco 2019",
    "item-name-113": "Arzuaga Crianza",
    "item-name-114": "La Felisa Emilio Moro",
    "item-name-115": "Cair Cuve Magnum",
    "item-name-116": "La Pinnaleta",
    "item-name-117": "Malleolus",
    "item-name-118": "Abadía Retuerta Selección Especial",
    "item-name-119": "Francisco Barona",
    "item-name-120": "Tomás Postigo 3 Año",
    "item-name-121": "Valduero I Cepa",
    "item-name-122": "A&M Asenjo Manso",
    "item-name-123": "Garmón 2019",
    "item-name-124": "Pago Carraovejas",
    "item-name-125": "Punto Geodésico",
    "item-name-126": "Raza Carmelo Rodero",
    "item-name-127": "Aalto",
    "item-name-128": "Dehesa Canónigos Solideo",
    "item-name-129": "Valduero Alta RVA",
    "item-name-130": "Un Sueño Pago de los Capellanes",
    "item-name-131": "Arzuaga Reserva Especial 2018",
    "item-name-132": "Tomás Postigo 5º Año",
    "item-name-133": "Tomás Postigo Magnum 3 Año",
    "item-name-134": "Francisco Barona Finca Las Dueñas",
    "item-name-135": "Sed de Caña",
    "item-name-136": "Aalto PS",
    "item-name-137": "Malleolus Valderramiro",
    "item-name-138": "Valduero Gran RVA",
    "item-name-139": "Luis Sanz Gran RVA",
    "item-name-140": "Tomás Postigo Rebollo Magnum",
    "item-name-141": "Valbuena 5º",
    "item-name-142": "Tomás Postigo Vinificación Integral Magnum",
    "item-name-143": "Doroteo Pago de los Capellanes",
    "item-name-144": "La Rejadora",
    "item-name-145": "Prima",
    "item-name-146": "Lorca Malbec",
    "item-name-147": "San Román",
    "item-name-148": "Platón Divina",
    "item-name-149": "Latarce",
    "item-name-150": "Syrah Matasnos",
    "item-name-151": "Pintia",
    "item-name-152": "Cartago",
    "item-name-153": "Alquez",
    "item-name-154": "Museum RVA",
    "item-name-155": "Albeniz Torre",
    "item-name-156": "Sommos Colección Syrah",
    "item-name-157": "Mauro",
    "item-name-158": "Mauro VS",
    "item-name-159": "Terreus",
    "item-name-160": "El Maquinista",
    "item-name-161": "Rioja Ondarre Crianza",
    "item-name-162": "Amador Medrano Los Sotillos",
    "item-name-163": "Bai Gorri",
    "item-name-164": "Beronia Edición Limitada",
    "item-name-165": "Amador Medrano Las Aguzaderas",
    "item-name-166": "La Montesa",
    "item-name-167": "Amaren",
    "item-name-168": "Luis Cañas Reserva 2018",
    "item-name-169": "Murua Rioja",
    "item-name-170": "Colección Privada Beronia",
    "item-name-171": "Los Sotillos",
    "item-name-172": "Macán Oro",
    "item-name-173": "Macán Clásico",
    "wine-grape-0": "Godello – elegant und geschmeidig, mit lebendiger Säure und Zitrus-Hintergrund",
    "wine-grape-1": "Godello – ausdrucksstark, mit Aromen von Steinobst und Mandelnoten im Abgang",
    "wine-grape-2": "Godello, Doña Blanca, Treixadura – frisch und mineralisch mit Noten von Gras und weißen Blüten",
    "wine-grape-3": "Godello – Referenz der D.O., rein und frisch mit blumigen und mineralischen Noten",
    "wine-grape-4": "Godello – geräumig und elegant, mit Nuancen von reifen Früchten und Schiefermineralien",
    "wine-grape-5": "Godello – Reifung auf der Hefe, die für Cremigkeit, Komplexität und große Nachhaltigkeit sorgt",
    "wine-grape-6": "Godello – einzigartiges Weingut in Bierzo, mineralisch und spannungsgeladen mit perfekter Säure",
    "wine-grape-7": "Albariño – Starterwein, der den atlantischen Charakter der D.O. vermittelt. Rias Baixas",
    "wine-grape-8": "Albariño – frisch und aromatisch, leicht zu trinken und mit gutem Preis-Leistungs-Verhältnis",
    "wine-grape-9": "Albariño – jung und atlantisch, mit Zitrus-, Pfirsich- und einem Hauch salziger Note",
    "wine-grape-10": "Albariño – ausdrucksstark und fruchtig, mit guter Säure und Kräuterhintergrund",
    "wine-grape-11": "Albariño – von O Salnés, sehr fruchtig, frisch und rein mit anhaltendem Abgang",
    "wine-grape-12": "Albariño – elegant und komplex, mit einer Reifung, die ihm Tiefe und Charakter verleiht",
    "wine-grape-13": "Treixadura – Königinsorte des Ribeiro, frisch und blumig mit einem subtilen und sauberen Abgang",
    "wine-grape-14": "Treixadura – von Hangreben, lebendig und mineralisch mit einem Hauch aromatischem Gras",
    "wine-grape-15": "Treixadura, Godello, Albariño – Coupage einheimischer Ribeiro-Sorten mit viel Ausdruck",
    "wine-grape-16": "Godello – jung und direkt, mit der für Valdeorras typischen Säure und Mineralität",
    "wine-grape-17": "Godello – Fassreifung, die für Komplexität und elegante Toasts sorgt",
    "wine-grape-18": "Godello – einzigartig und charakteristisch, mit einem sehr ausgeprägten atlantischen Charakter und großer Frische",
    "wine-grape-19": "Godello – aus Valdeorras, ausdrucksstark und angespannt mit lebendiger Säure und mineralischem Abgang",
    "wine-grape-20": "Mencía – frisch und fruchtig, mit den für diese galizische Sorte typischen Noten von Kirsche und Veilchen",
    "wine-grape-21": "Mencia – elegant und mineralisch, mit weichen Tanninen und einem langen, würzigen Abgang",
    "wine-grape-22": "Mencia – saftig und zugänglich, mit guten roten Früchten und kräuterigem Terroirhintergrund",
    "wine-grape-23": "Mencia – jung und süß, mit frischen Früchten und weichen Tanninen, ideal für einen Aperitif",
    "wine-grape-24": "Mencía – aus der Ribeira Sacra, mineralisch und vertikal mit der Eleganz des Granit-Terroirs",
    "wine-grape-25": "Mencía – aus Weinbergen an den Hängen der Ribeira Sacra, mineralisch und spannungsgeladen mit konzentrierter Frucht",
    "wine-grape-26": "Mencía – aus Bierzo, blumig und stark parfümiert mit seidigen Tanninen und lebendiger Säure",
    "wine-grape-27": "Mencia – frische Aromen von roten und violetten Früchten mit eleganten Bierzo-Tanninen",
    "wine-grape-28": "Brancellao, Sousón, Ferrón – Mischung einheimischer Ribeiro-Tinten, einzigartig und ausdrucksstark",
    "wine-grape-29": "Mencía, Garnacha Tintorera – kraftvolle und ausdrucksstarke Mischung mit reifen schwarzen Früchten",
    "wine-grape-30": "Mencía – von Álvaro Palacios, blumig und elegant, gilt als weltweite Referenz für diese Sorte",
    "wine-grape-31": "Sousón – wiedergewonnene einheimische galizische Sorte, intensiv und komplex mit großartigem Charakter",
    "wine-grape-32": "Chardonnay, Pinot Noir, Pinot Meunier – klassischer, frischer und ausgewogener Champagner",
    "wine-grape-33": "Tinto Fino – jung mit Eichenreifung, zugänglich und fruchtig mit gut integrierten Holznoten",
    "wine-grape-34": "Tinto Fino – sanfter Durchgang durch das Fass, jung und fruchtig mit dem typischen Charakter der Aranda-Region",
    "wine-grape-35": "Tinto Fino – Vorspeisenwein von Bodegas Emilio Moro, fruchtig und leicht zu trinken",
    "wine-grape-36": "Tinto Fino – aus jahrhundertealten Reben, konzentriert und tiefgründig mit viel Terroir-Persönlichkeit",
    "wine-grape-37": "Tinto Fino – von Emilio Moro, aus seinem eigenen Weingut, jung und konzentriert mit viel roter Frucht",
    "wine-grape-38": "Tinto Fino – frisch und fruchtig von Bodegas Prios Maximus, mit gutem Preis-Leistungs-Verhältnis",
    "wine-grape-39": "Tinto Fino – von Emilio Moro, im Eichenfass gereift mit sehr lebendiger und zugänglicher Frucht",
    "wine-grape-40": "Tinto Fino – aus Convento San Francisco, jung und zugänglich mit Noten von frischen Früchten",
    "wine-grape-41": "Tinto Fino – Passage durch Bodegas Tamaral-Eichenholz, frisch und fruchtig mit einer würzigen Note",
    "wine-grape-42": "Tinto Fino – Terroirwein, mineralischer und frischer Wein mit guter natürlicher Säure",
    "wine-grape-43": "Tinto Fino, Cabernet Sauvignon, Merlot – modern und fruchtig mit internationaler Präsenz",
    "wine-grape-44": "Tinto Fino – kurze Passage durch Eichenholz, fruchtig und zugänglich, aus einer der Referenzen der D.O.",
    "wine-grape-45": "Tinto Fino – einer der ältesten Jahrgänge der D.O., mit reifer Frucht und guter Reifung",
    "wine-grape-46": "Tinto Fino – aus wilden Reben, wilder und mineralischer Charakter mit großer Authentizität",
    "wine-grape-47": "Tinto Fino – von alten Reben in La Horra, elegant und terroiristisch mit viel Charakter",
    "wine-grape-48": "Tinto Fino – 9 Monate im Fass, kraftvoll und würzig mit einer großartigen Persönlichkeit",
    "wine-grape-49": "Tinto Fino – gereift von Bodegas Tamaral, ausgewogen und gastronomisch mit guter Struktur",
    "wine-grape-50": "Tinto Fino – klassische Reifung, ausgewogen und sehr vielseitig zu Fleisch und Käse",
    "wine-grape-51": "Tinto Fino – von Bodegas Valduero, elegant und mineralisch mit einem großartigen Ausdruck des Terroirs",
    "wine-grape-52": "Tinto Fino, Cabernet Sauvignon, Merlot – modern und samtig mit Noten von schwarzen Früchten und Gewürzen",
    "wine-grape-53": "Tinto Fino – aus einem jahrhundertealten Einzelweinberg, konzentriert und terroiristisch mit viel Persönlichkeit",
    "wine-grape-54": "Tinto Fino – von Bodegas Rivera, kraftvoll und großzügig mit reifen schwarzen Früchten und gut integrierter Eiche",
    "wine-grape-55": "Tinto Fino – aus einem einzigartigen, mineralischen und eleganten Weingut, gereift in französischer Eiche",
    "wine-grape-56": "Tinto Fino – klassische Reifung in amerikanischer und französischer Eiche, ausgewogen und sehr elegant",
    "wine-grape-57": "Tinto Fino, Cabernet Sauvignon – klassische Reifung mit viel Struktur und langem würzigem Abgang",
    "wine-grape-58": "Tinto Fino – charakteristische Reifung mit langen Mazerationen, kraftvoll und sehr ausdrucksstark",
    "wine-grape-59": "Tinto Fino – ausdrucksstark und konzentriert, gereift in französischer und amerikanischer Eiche",
    "wine-grape-60": "Tinto Fino – ältere Version, komplex und mineralisch mit langem Abgang im Mund",
    "wine-grape-61": "Tinto Fino, Cabernet Sauvignon, Merlot – klassisch und ausgewogen, mit gut integrierten Tanninen",
    "wine-grape-62": "Tinto Fino – aus Emilio Moros eigenem Nachlass, elegant und mineralisch, ein weiterer Schritt in der Sammlung",
    "wine-grape-63": "Tinto Fino – gleiche Cuvée in Magnum, ideal zum Teilen und mit besserer Entwicklung",
    "wine-grape-64": "Tinto Fino – aus einer einzigen Parzelle, ausdrucksstark und einzigartig mit großem Reifepotenzial",
    "wine-grape-65": "Tinto Fino – Emilio Moros großartiger Wein, seidig und komplex mit ausgewählten alten Reben",
    "wine-grape-66": "Tempranillo, Cabernet Sauvignon, Syrah – außerhalb der D.O., elegant und komplex aus der Region Sardón",
    "wine-grape-67": "Tinto Fino – Autorenauswahl alter Reben, kraftvoll und mit großer Persönlichkeit",
    "wine-grape-68": "Tinto Fino – 3 Jahre vollständige Reifung, weich und elegant mit einem langen Abgang und Noten von Zedernholz",
    "wine-grape-69": "Tinto Fino – von Bodegas Valduero, Auswahl einer einzigartigen Sorte mit großartiger Struktur und Eleganz",
    "wine-grape-70": "Tinto Fino – Familienprojekt aus jahrhundertealten Reben, tiefgründig und intensiv",
    "wine-grape-71": "Tinto Fino – von Cillar de Silos, von alten Gumiel de Mercado-Reben, komplex und seidig",
    "wine-grape-72": "Tinto Fino, Cabernet Sauvignon, Merlot – einer der Großen der D.O., tiefgründig und ausgewogen",
    "wine-grape-73": "Tinto Fino – aus ausgewählten Parzellen, mineralisch und terroirisch mit großer Präzision",
    "wine-grape-74": "Tinto Fino – der maximale Ausdruck von Carmelo Rodero, Auswahl alter Reben und großartiger Jahrgang",
    "wine-grape-75": "Tinto Fino – aus alten Reben, seidig und elegant mit schwarzen Früchten und edlen Gewürzen",
    "wine-grape-76": "Tinto Fino – besondere Reserve mit langer Reifung, elegant und komplex mit endlosem Abgang",
    "wine-grape-77": "Tinto Fino – hohe Reserve aus Valduero, sehr lange Reifung mit beeindruckender Komplexität",
    "wine-grape-78": "Tinto Fino – aus ausgewählten Parzellen von Capellanes, elegant und mit großem Reifepotenzial",
    "wine-grape-79": "Tinto Fino – ein Reservat mit maximalem Ausdruck, langer Reifung und großer aromatischer Komplexität",
    "wine-grape-80": "Tinto Fino – 5 Jahre gereift, einer der Großen des Duero, seidig und tief",
    "wine-grape-81": "Tinto Fino – 3 Jahre im Magnum gereift für mehr Entwicklung und Ausdruck",
    "wine-grape-82": "Tinto Fino – einzigartiges Anwesen, der maximale Ausdruck von Francisco Barona, Sammlerstück",
    "wine-grape-83": "Tinto Fino – Ikone der Bodegas Montecastro, mit jahrhundertealten Reben, kraftvoll und gealtert",
    "wine-grape-84": "Tinto Fino – Pago de Santa Cruz, Ikone des Weinguts, tiefgründig und mit großem Reifepotenzial",
    "wine-grape-85": "Tinto Fino – aus einem jahrhundertealten Einzelweinberg von Emilio Moro, einem der ganz Großen Spaniens",
    "wine-grape-86": "Tinto Fino – großartige Reserve aus Valduero, ein Maßstab der D.O. mit jahrzehntelanger Geschichte",
    "wine-grape-87": "Tinto Fino – große Reserve an langer Reifung, komplex und entwickelt mit großer Eleganz",
    "wine-grape-88": "Tinto Fino – aus einem jahrhundertealten Rebollo-Grundstück, in Magnum, dem Dach der Postigo-Sammlung",
    "wine-grape-89": "Tinto Fino, Merlot – der Bruder des legendären Vega Sicilia, 5 Jahre Reifung und enorme Komplexität",
    "wine-grape-90": "Tinto Fino – ganzheitliche Weinbereitung in Eiche, der maximale Ausdruck des Weinguts in Magnum",
    "wine-grape-91": "Tinto Fino – der maximale Ausdruck von Pago de los Capellanes, fragen Sie nach der Verfügbarkeit",
    "wine-grape-92": "Tinta de Toro – jung und kraftvoll, mit reifen dunklen Früchten und dem robusten Charakter der Gegend",
    "wine-grape-93": "Tinta de Toro – von Bodegas Tardencuba, strukturiert und mit Persönlichkeit, in Eichenfässern gereift",
    "wine-grape-94": "Malbec – argentinische Sorte, eingepflanzt in Toro, kraftvoll und mit Noten von Pflaume und Veilchen",
    "wine-grape-95": "Tinta de Toro – aus Maurodos (Telmo Rodríguez), alte Reben mit intensivem und mineralischem Charakter",
    "wine-grape-96": "Tinta de Toro – von Bodegas Divina, kraftvoll und mit einer großen Konzentration an schwarzen Früchten",
    "wine-grape-97": "Tinta de Toro – von Bodegas Latarce, kraftvoll und mit reifen dunklen Früchten und reifen Tanninen",
    "wine-grape-98": "Syrah – mediterraner Ausdruck dieser Sorte in Toro, würzig und mit viel dunkler Frucht",
    "wine-grape-99": "Tinta de Toro – von Vega Sicilia, der eleganteste Ausdruck von Toro, komplex und fein",
    "wine-grape-100": "Tinta de Toro – von Bodegas Frontio, Wein von großer Konzentration und langer Reifung",
    "wine-grape-101": "Garnacha – einheimische Sorte aus der Sierra de Gredos, mineralisch und mit frischen roten Früchten",
    "wine-grape-102": "Tempranillo – Cigales zurückhaltend, ausgewogen und klassisch mit guter Struktur",
    "wine-grape-103": "Tempranillo – aus der Gegend von Cigales, kraftvoll und strukturiert mit Noten von reifen Früchten",
    "wine-grape-104": "Syrah – von Bodegas Sommos in Aragón, intensiv und würzig mit großer Konzentration",
    "wine-grape-105": "Tempranillo, Garnacha – die Ikone außerhalb der D.O. aus Tudela del Duero, kraftvoll und komplex",
    "wine-grape-106": "Tempranillo, Garnacha – Ausgewählte Ernte aus alten Reben, ein monumentaler Wein",
    "wine-grape-107": "Tempranillo – von Mauro, der exklusivste Wein des Weinguts, aus alten Reben und großer Reifung",
    "wine-grape-108": "Tempranillo – jung und fruchtig, lebendig und zugänglich mit dem Siegel der Rioja Alavesa",
    "wine-grape-109": "Tempranillo, Garnacha – klassische und ausgewogene Riojan-Reifung von Bodegas Ondarre",
    "wine-grape-110": "Tempranillo – aus ausgewählten Parzellen mit größerem Ausdruck von Terroir und Komplexität",
    "wine-grape-111": "Tempranillo – aus Rioja Alavesa, frisch und mineralisch mit feinen Tanninen und guter Säure",
    "wine-grape-112": "Tempranillo, Mazuelo, Graciano – Sonderausgabe mit größerer Komplexität und Persönlichkeit",
    "wine-grape-113": "Tempranillo – vom Weingut Las Aguzaderas, der charakteristische Wein des Weinguts, mineralisch und tiefgründig",
    "wine-grape-114": "Garnacha, Tempranillo, Mazuelo – von Palacios Remondo, elegante und sehr ausdrucksstarke Rioja-Garnacha",
    "wine-grape-115": "Tempranillo, Graciano – Abel Mendozas moderner Riojan-Klassiker, elegant und ausgewogen",
    "wine-grape-116": "Tempranillo, Graciano – elegante und ausgereifte Reserve von einem der führenden Weingüter",
    "wine-grape-117": "Tempranillo, Graciano, Mazuelo – klassische Reservate der Bodegas Murua in Rioja Alavesa",
    "wine-grape-118": "Tempranillo – besondere Selektion aus Beronia, mit mehr Charakter und langer Reifung in Eichenfässern",
    "wine-grape-119": "Tempranillo – aus der einzigen Parzelle von Amador Medrano, der Spitze des Weinguts mit großartigem Ausdruck",
    "wine-grape-120": "Tempranillo – das Spitzenprodukt der Macán-Kollektion, Wein aus besonderen Jahrgängen, fragen Sie nach der Verfügbarkeit",
    "wine-grape-121": "Tempranillo – zugänglichere Version von Macán, fruchtig und elegant, fragen Sie nach der Verfügbarkeit",
    "allergen-0": "Lupinen",
    "allergen-1": "Sellerie",
    "allergen-2": "Erdnüsse",
    "allergen-3": "Glutengetreide",
    "allergen-4": "Krebstiere",
    "allergen-5": "Schalenfrüchte",
    "allergen-6": "Eier",
    "allergen-7": "Milchprodukte",
    "allergen-8": "Weichtiere",
    "allergen-9": "Senf",
    "allergen-10": "Sesam",
    "allergen-11": "Soja",
    "allergen-12": "Sulfite",
    "allergen-13": "Fisch",
    "allergen-legend-title": "Allergen-Referenz"
  }
};
